### ISSUE TITLE
Getting error when using the @polkadot/api v0.81.1

### ISSUE THREAD

**Issue by satyamakgec** [polkadot-js/api#1026]
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'bs58'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/satyamagrawal/Repositories/Rust-projects/Project1/scripts/node_modules/@polkadot/util-crypto/address/decode.js:10:34)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

**Comment by jacogr** [comment]
Thank you, this one is known and a fix is already in master. (Was caused by movement of functionality between packages upstream in util) As a work-around, any of the following would work -

- install the bs58 dep manually
- add the `@polkadot/keyring` dep
- use the `@polkadot/api@beta` (master)
