### ISSUE TITLE
arg[0] is undefined in decorateMulti from /api/src/Base.ts

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#1113]
On a recent v2.0 Substrate node

The test "derive e2e › retrieves all staking info (for controller)" fails with the following:
```bash
    TypeError: Cannot read property 'creator' of undefined

      560 |           // the input is a QueryableStorageEntry, convert to StorageEntry
      561 |           Array.isArray(arg)
    > 562 |             ? [arg[0].creator, ...arg.slice(1)]
          |                       ^
      563 |             : [arg.creator] as any
      564 |         );
      565 | 

      at creator (packages/api/src/Base.ts:562:23)
          at Array.map (<anonymous>)
      at Object.map [as queryMulti] (packages/api/src/Base.ts:559:30)
      at queryMulti (packages/api-derive/src/staking/info.ts:125:9)
      at SwitchMapSubscriber.withControllerLedger [as project] (packages/api-derive/src/staking/info.ts:167:17)
      at SwitchMapSubscriber.Object.<anonymous>.SwitchMapSubscriber._next (node_modules/rxjs/src/internal/operators/switchMap.ts:123:21)
      at SwitchMapSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at RefCountSubscriber.Object.<anonymous>.Subscriber._next (node_modules/rxjs/src/internal/Subscriber.ts:139:22)
      at RefCountSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at ReplaySubject.Object.<anonymous>.Subject.next (node_modules/rxjs/src/internal/Subject.ts:70:17)
      at ReplaySubject.Object.<anonymous>.ReplaySubject.nextInfiniteTimeWindow (node_modules/rxjs/src/internal/ReplaySubject.ts:46:15)
      at ConnectableSubscriber.Object.<anonymous>.Subscriber._next (node_modules/rxjs/src/internal/Subscriber.ts:139:22)
      at ConnectableSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at Object.next [as callback] (packages/rpc-core/src/index.ts:183:22)
      at WsProvider.callback [as onSocketMessageSubscribe] (packages/rpc-provider/src/ws/Provider.ts:352:15)
      at WsProvider.onSocketMessageSubscribe [as onSocketMessageResult] (packages/rpc-provider/src/ws/Provider.ts:323:16)
      at WebSocket.onSocketMessageResult (packages/rpc-provider/src/ws/Provider.ts:292:14)
      at WebSocket.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at WebSocketImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at WebSocketImpl._onMessageReceived (node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:208:10)
      at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:720:20)
      at Receiver.dataMessage (node_modules/ws/lib/receiver.js:414:14)
      at Receiver.getData (node_modules/ws/lib/receiver.js:346:17)
      at Receiver.startLoop (node_modules/ws/lib/receiver.js:133:22)
      at Receiver._write (node_modules/ws/lib/receiver.js:69:10)
      at Socket.socketOnData (node_modules/ws/lib/websocket.js:795:35)
```

linked to https://github.com/polkadot-js/apps/issues/1386

**Comment by Stefie** [comment]
There are quite a few failing tests at the moment. The derived ones were last passing on tuesday, but since then a lot changed in the API and in Substrate.
