### ISSUE TITLE
Use multi-variant enum as an extrinsic parameter

### ISSUE THREAD

**Issue by anakornk** [polkadot-js/api#1615]
I'm having a problem with using multi-variant enum as an extrinsic parameter. In this example, my enum is ValueType and i'm trying to call set_enum which has ValueType enum as one of its parameters through polkadot js api. When the enum only has one variant (any of the 4), all works fine. I could also combine uint32 and uint64. However, the other combinations will report an error. For instance, when i tried having all 4 variants together, I could submit an extrinsic with uint32 and uint64, but using either Bool or Char32 will give me an error.

Enum
```
#[derive(Clone, Encode, Decode, PartialEq, Eq, RuntimeDebug)]
pub enum ValueType {
	Char32([u8; 32]),	
	Uint32(u32),
	Uint64(u64),
	Bool(bool),
}
```
```
		fn set_enum(origin, value: ValueType) -> Result {
			// Check if signed
			let sender = ensure_signed(origin)?;
			Ok(())
		}
```

Call set_enum from polkadotjs api
```
api.tx.content
    .setEnum({
      char32: "0x12345678123456781234567812345678"
    })
    .signAndSend(alicePair, { nonce }, ({ events = [], status }) => { ... }
```

Error
```
2019-11-28 12:26:15        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: Content.0")): RuntimeApi("Execution(ApiError(\"
2019-11-28 12:26:15             DRR: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: Content.0")): RuntimeApi("Execution(ApiError(\"
    at errorHandler (/Users/anakornk/Code/graph4w3/graph-js-sdk/node_modules/@polkadot/rpc-core/index.js:259:26)
    at /Users/anakornk/Code/graph4w3/graph-js-sdk/node_modules/@polkadot/rpc-core/index.js:233:9
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
```

Seems like there is something wrong with the encoding/decoding part. Am i missing anything?

**Comment by jacogr** [comment]
There really doesn't seem anything wrong above, well, not from what I can see. It should handle the enum correct. Like the u32 & u64, the `[u8; 32]` should work.

I would appreciate a quick test though, just to see if there is maybe a discrepancy as to how fixed vectors are handled. (Just as a starting point of trying to understand what is breaking and where)

Could you change the type signature for the enum to the following -

```
ValueType: { 
  Char32: "H256",
  Uint32: "u32",
  Uint64: "u64"
}
```

And then just test again with the Char32 as you have above. (The 2 types here are equivalent in size and codec representation, just want to see if at least part of it is a fixed vec issue.) This still doesn't explain why `bool` (which is just a single byte), also creates issues.

**Comment by anakornk** [comment]
Definition of ValueType in Rust
```
#[derive(Clone, Encode, Decode, PartialEq, Eq, RuntimeDebug)]
pub enum ValueType {
	Char32(primitives::H256),	
	Uint32(u32),
	Uint64(u64),
}
```

Registering types on polkadot-js/api
```
     ValueType: {
        _enum: {
          Uint32: "u32",
          Uint64: "u64",
          Char32: "H256",
        }
      }
```

Re-ran the test again with Char32, got a different error this time:
```
2019-11-28 16:37:33        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof
2019-11-28 16:37:33             DRR: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof
    at errorHandler (/Users/anakornk/Code/graph4w3/graph-js-sdk/node_modules/@polkadot/rpc-core/index.js:259:26)
    at /Users/anakornk/Code/graph4w3/graph-js-sdk/node_modules/@polkadot/rpc-core/index.js:233:9
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
```

Also, tried testing uint64 and uint32 with the above config. Both no longer works now.
```
2019-11-28 16:44:24        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: Content.0")): RuntimeApi("Execution(ApiError(\"
2019-11-28 16:44:24             DRR: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: Content.0")): RuntimeApi("Execution(ApiError(\"
```

---
I did some additional tests and tried only registering Char32 on the js side. It works.
```
      ValueType: {
        _enum: {
          // Uint32: "u32",
          // Uint64: "u64",
          Char32: "H256",
        }
      }
```
However, if i tried registering only uint32 or uint64, i get the same error as before:
```
2019-11-28 16:41:58        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: Content.0")): RuntimeApi("Execution(ApiError(\"
```

**Comment by jacogr** [comment]
Thanks for the extensive play-through. Especially the last one is really interesting, it is like any tuple with multiple entries are doing something really, really weird here. (And they are used extensively even in the substrate/polkadot codebases, so this is, well, beyond weird)

Will have to dig around for some ideas. Atm, stumped.

**Comment by jacogr** [comment]
Ahh, wait in your example you have this for Rust -

```rust
#[derive(Clone, Encode, Decode, PartialEq, Eq, RuntimeDebug)]
pub enum ValueType {
	Char32(primitives::H256),	
	Uint32(u32),
	Uint64(u64),
}
```

and then this on the JS side -

```js
ValueType: {
        _enum: {
          Uint32: "u32",
          Uint64: "u64",
          Char32: "H256",
        }
      }
```

The ordering needs to match for enums, the index is used to encode the type following.

**Comment by anakornk** [comment]
Ahh, re-did all the tests, everything is working now. I thought i did tried changing the ordering. Thanks! 

---

One last problem i had was with polkadot-js/apps. Not sure if it is the same issue as this one here: https://github.com/polkadot-js/apps/pull/1726
There is this react rendering problem when changing the enum variant in 'Extrinsics' tab. The screen just goes white.
```
backend.js:6 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Comment by jacogr** [comment]
Would log the above in the apps repo, that is a bug.
