### ISSUE TITLE
signAndSend throw RPC-CORE: submitExtrinsic(extrinsic: Extrinsic)   error

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#1630]
> version  @polkadot/api": "0.97.1"

``` 
  const nonce = await api.query.system.accountNonce(keyring.alice.address);
  (await api.tx.balances.transfer(keyring.bob.address, 12345).signAndSend(keyring.alice, {
    nonce
  })).toHex(); // just with the callback
```

catch error
```
2019-12-03 17:56:41        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Invalid address variant")): RuntimeApi("Execution(ApiError(\"
(node:15085) UnhandledPromiseRejectionWarning: Error: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Invalid address variant")): RuntimeApi("Execution(ApiError(\"
    at CatchSubscriber.selector (sub/node_modules/@polkadot/rpc-core/index.js:211:38)
    at CatchSubscriber.error (sub/node_modules/rxjs/internal/operators/catchError.js:48:31)
    at MapSubscriber.Subscriber._error (sub/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (sub/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SwitchMapSubscriber.OuterSubscriber.notifyError (sub/node_modules/rxjs/internal/OuterSubscriber.js:26:26)
    at InnerSubscriber._error (sub/node_modules/rxjs/internal/InnerSubscriber.js:31:21)
    at InnerSubscriber.Subscriber.error (sub/node_modules/rxjs/internal/Subscriber.js:72:18)
    at CombineLatestSubscriber.OuterSubscriber.notifyError (sub/node_modules/rxjs/internal/OuterSubscriber.js:26:26)
    at InnerSubscriber._error (sub/node_modules/rxjs/internal/InnerSubscriber.js:31:21)
    at InnerSubscriber.Subscriber.error (sub/node_modules/rxjs/internal/Subscriber.js:72:18)
(node:15085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by jacogr** [comment]
On which node type? Any customizations? The addresses are passed as the normal SCALE-encoded variant for the default Substrate Address type.

**Comment by freehere107** [comment]
Fix, ``Address`` type covered by H160.
