### ISSUE TITLE
sign transaction by polkadot.js error

### ISSUE THREAD

**Issue by qc9090** [polkadot-js/api#1646]
i use the new version of polkadot.js(0.99.0-beta.3) to sign transaction, but it respond error message as below, what is the possible problem?
Error: createType(Call):: Struct: failed on 'args':: Struct: failed on 'value':: Assertion failed
    at createTypeUnsafe (/data/prochain-sign-server/node_modules/@polkadot/types/codec/create/createType.js:73:11)
    at createType (/data/prochain-sign-server/node_modules/@polkadot/types/codec/create/createType.js:89:10)
    at extrinsicFn (/data/prochain-sign-server/node_modules/@polkadot/metadata/Decorated/extrinsics/fromMetadata/createUnchecked.js:38:39)
    at Object.decorated [as unlock] (/data/prochain-sign-server/node_modules/@polkadot/api/base/Decorate.js:217:22)
    at fs.readFile (/data/prochain-sign-server/index.js:365:29)

**Comment by jacogr** [comment]
You will need . to show the code as to what you are calling. That sounds like a number being incorrectly converted, the "assertion failed" issues comes from the `bn.js` library.
