### ISSUE TITLE
Error querying nominators (cannot read property next of undefined)

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/api#1675]
When trying to query all the nominators from a `linked_map`:

```
let result = await api.query.staking.nominators();
console.log(JSON.stringify(result));
```

I get the error:

```
TypeError: Cannot read property 'next' of undefined
    at SwitchMapSubscriber.project (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/@polkadot/api/base/Decorate.js:289:19)
    at SwitchMapSubscriber._next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/operators/switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/ReplaySubject.js:48:31)
    at ConnectableSubscriber.Subscriber._next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DistinctUntilChangedSubscriber._next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/Subscriber.js:66:18)
    at CatchSubscriber.Subscriber._next (/Users/shawntabrizi/Documents/GitHub/substrate-one-million-remarks/node_modules/rxjs/internal/Subscriber.js:89:26)
```

But calling `validators()` work just fine :)

**Comment by jacogr** [comment]
Nominators were migrated a short while ago. And it was actually tested alongside. Will have to check the detection logic for the 3 branches (v1, ?2-old and v2-new) here, it is obviously not following the right path on detecting. 

Could also be that the storage versioning (which is used here) is different than expected or just handled incorrectly, there were some churn right at the end which may not have been caught.

**Comment by shawntabrizi** [comment]
I was on latest CC3 and using `0.99.1` if that helps.

I am not blocked on this, was able to query all the items we needed using the raw `getStorage()` RPC :)

**Comment by jacogr** [comment]
I am less worried about you being blocked than having a bug ;)
