### ISSUE TITLE
Unable to decode storage system.events for Kusama block 92874

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/api#1736]
I get the following at block 92874 ([polkascan](https://polkascan.io/pre/kusama-cc3/block/92874))
```bash
Unable to decode storage system.events: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 15, in Normal, Operational
2020-01-21 18:13:29        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 15, in Normal, Operational
2020-01-21 18:13:29            MAIN: Error: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Struct: failed on 'data':: Unable to create Enum via index 15, in Normal, Operational
    at CatchSubscriber.pipe.error [as selector] (/home/thib/github/paritytech/Nomidot/node_modules/@polkadot/rpc-core/index.js:193:38)
    at CatchSubscriber.error (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/operators/catchError.ts:132:23)
    at MapSubscriber._next (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/operators/map.ts:86:24)
    at MapSubscriber.Subscriber.next (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/Subscriber.ts:99:12)92874
    at SwitchMapSubscriber.notifyNext (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/operators/switchMap.ts:172:24)
    at InnerSubscriber._next (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at CombineLatestSubscriber.notifyNext (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/observable/combineLatest.ts:313:26)
    at InnerSubscriber._next (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/InnerSubscriber.ts:17:17)
    at InnerSubscriber.Subscriber.next (/home/thib/github/paritytech/Nomidot/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
```

Reproducible in the [js console](https://polkadot.js.org/apps/#/js). With the block before all good, the 92874 fails:
```js
async function logMethod(blockHash){
  const events = await api.query.system.events.at(blockHash);
  events.map(
        ({ event: { method } }) =>
          console.log('method',method)
      );
}

const blockHashFine = "0x88bfb8baf0e8e5e192b911b80aed45e49f27b50fa91d217a2ca71c6dd1e2c53d"; //92873 working fine
const blockHashFailing = "0xc67e368912d8b0a824f917fff7ef3885e4bf867f07df99441368eb234b05b4ab"; //92874 failing

logMethod(blockHashFine).catch(e => console.error(e));
logMethod(blockHashFailing).catch(e => console.error(e));
```

**Comment by jacogr** [comment]
If you want to time-travel, you need to ensure you have the correct types at that block. (The API always only injects the latest, not historic)

Additionally, between the various upgrades modules have been changed in addition to the types. Same thing applies. Ensure you have the metadata for that block before decoding. 

The API is optimized for current queries which maps to the current types.

**Comment by jacogr** [comment]
PS: the above specifically is caused by the changes in DispatchError, older versions on the runtime is on a previous version

**Comment by jacogr** [comment]
See also  

https://github.com/polkadot-js/api/issues/1648

and

https://github.com/polkadot-js/api/issues/845

For similar issues. None of there are effectively supported as it stands - for trying to traverse the whole chain, a specific solution like Polkascan fits the bill. (It checks for metadata as a it changes and adjusts the types, managing multiple versions)

**Comment by Tbaut** [comment]
OOps, I forgot to mention that we actually do update the metadata for each block, here the accurate version of the snippet, with the same error (there's no bump between those 2):

```js
let currentSpecVersion = api.createType('u32', -1);

async function updateMetaData(blockHash){
  // check spec version
  const runtimeVersion = await api.rpc.state.getRuntimeVersion(blockHash);
  const newSpecVersion = runtimeVersion.specVersion;

  console.log(`newSpecVersion: ${newSpecVersion}`)
  console.log(`currentSpecVersion: ${currentSpecVersion}`)

    // if spec version was bumped, update metadata in api registry
  if (newSpecVersion.gt(currentSpecVersion)) {
    console.log(`bumped spec version to ${newSpecVersion}, fetching new metadata`);
    const rpcMeta = await api.rpc.state.getMetadata(blockHash);
    currentSpecVersion = newSpecVersion;
    api.registry.setMetadata(rpcMeta);
  }
}
    
async function logMethod(blockHash){
  const events = await api.query.system.events.at(blockHash);
  events.map(
        ({ event: { method } }) =>
          console.log('method',method)
      );
}

const blockHashFine = "0x88bfb8baf0e8e5e192b911b80aed45e49f27b50fa91d217a2ca71c6dd1e2c53d"; //92873 working fine
const blockHashFailing = "0xc67e368912d8b0a824f917fff7ef3885e4bf867f07df99441368eb234b05b4ab"; //92874 failing

await updateMetaData(blockHashFine).then(() => logMethod(blockHashFine)).catch(e => console.error(e));
await updateMetaData(blockHashFailing).then(() => logMethod(blockHashFailing)).catch(e => console.error(e));
```

**Comment by jacogr** [comment]
It is the types, specifically DispatchError, as indicated above, see https://github.com/polkadot-js/api/blob/master/packages/api/src/base/typeInjector.ts#L33

(The above is NOT comprehensive, since types adjust to latest)

**Comment by Tbaut** [comment]
ah thanks for the code, we'll make sure to follow the type changes.
