### ISSUE TITLE
Metadata hex from node with custom pallet cannot re-create Metadata object

### ISSUE THREAD

**Issue by whalelephant** [polkadot-js/api#1838]
I am trying to re-create a metadata object with the data from RPC endpoint. 

**Setup** 

`git clone https://github.com/substrate-developer-hub/substrate-node-template.git my-node`

substrate node version 2.0.0-8b6fe66-x86_64-macos
polkadot.js v1.0.1

```
   const {TypeRegistry, Metadata} = require ('@polkadot/types')

   ... some api setup 

    const rpcMetadata = await api.rpc.state.getMetadata()

    const registry1 = new TypeRegistry()
    const registry2 = new TypeRegistry()

    const metadata_Obj = new Metadata(registry1, rpcMetadata)                // this works

    const metadata_Hex = new Metadata(registry2, rpcMetadata.toHex()) // this does not work

```

Below is the error message:

```
Error: Unable to create Enum via index 44, in Plain, Map, DoubleMap
    at assert (/directory-name/node_modules/@polkadot/util/assert.js:35:11)
    at createFromValue (/directory-name/node_modules/@polkadot/types/codec/Enum.js:44:20)
    at decodeFromValue (/directory-name/node_modules/@polkadot/types/codec/Enum.js:68:12)
    at Function.decodeEnum (/directory-name/node_modules/@polkadot/types/codec/Enum.js:119:12)
    at new Enum (/directory-name/node_modules/@polkadot/types/codec/Enum.js:95:26)
    at new <anonymous> (/directory-name/node_modules/@polkadot/types/codec/Enum.js:125:9)
    at new Type (/directory-name/node_modules/@polkadot/types/codec/create/registry.js:150:16)
    at decodeU8a (/directory-name/node_modules/@polkadot/types/codec/utils/decodeU8a.js:27:17)
    at decodeU8a (/directory-name/node_modules/@polkadot/types/codec/utils/decodeU8a.js:28:25)
    at decodeU8a (/directory-name/node_modules/@polkadot/types/codec/utils/decodeU8a.js:28:25)
```
___

I have tried the same for substrate node version 2.0.0-1b4b2c0-x86_64-macos which works without a problem. However for this version, the same error occurs when I have followed the instructions from [here](https://substrate.dev/docs/en/tutorials/creating-a-runtime-module/) to create a module in it's own pallet. I have not made any changes to the pallet template cloned from `git clone https://github.com/substrate-developer-hub/substrate-pallet-template.git my-pallet`. 
___

**Comment by jacogr** [comment]
Thanks for the detailed report, this is great. So going through -

1. This will actually return a metadata object already. Ao at this pint it will be parsed already - `const rpcMetadata = await api.rpc.state.getMetadata()` - so the output here is already`Metadata`

2. This works since it is creating the same object from an object - `const metadata_Obj = new Metadata(registry1, rpcMetadata)  `

3. On the next line we may have an issue in the `toHex` -  while it should work everywhere, we actually don't have tests for equivalence n metadata, i.e. the hex we generate matches the hex received from the node (e.g. when doing a simple curl to retrieve the metadata). 

So I am guessing, just because we never actually generate hex and use/test that anywhere (the API only consumes), there is an issue. (For a limited version, with calls-only there are tests, but even that took a bit of tweaking to get going - there is a lot of cleanup done along the way on the received data).
