### ISSUE TITLE
api.query.system.account is not a function

### ISSUE THREAD

**Issue by yqzzj** [polkadot-js/api#1992]
03_listen_to_balance_change run error.
How to run correctly?

..../03_listen_to_balance_change# yarn start
yarn run v1.22.0
$ node index.js
TypeError: api.query.system.account is not a function
    at main (/root/polkaeg/03_listen_to_balance_change/index.js:16:87)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)
^C

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/FAQ.html#my-chain-does-not-support-system-account-queries
