### ISSUE TITLE
system.eventTopics requires 2 arguments

### ISSUE THREAD

**Issue by whalelephant** [polkadot-js/api#2069]
I would like to get the mapping between the event topic and the events in blocks using `api.query.system.eventTopics(Hash)` according to [the doc](https://polkadot.js.org/api/substrate/storage.html#eventtopics-hash-vec-blocknumber-eventindex). 

**Code**

```
 let events = await api.query.system.eventTopics( '0xf06a8...')
```
**Error**
```
Error: system.eventTopics((), Hash) is a doublemap, requiring 2 arguments, 1 found
    at assert (/Users/belsy/entropyRepo/m2-feedback-cli/node_modules/@polkadot/util/assert.js:34:11)
    at doDoubleMap (/Users/belsy/entropyRepo/m2-feedback-cli/node_modules/@polkadot/api/util/validate.js:25:20)
    at extractStorageArgs (/Users/belsy/entropyRepo/m2-feedback-cli/node_modules/@polkadot/api/util/validate.js:46:12)
    at getArgs (/Users/belsy/entropyRepo/m2-feedback-cli/node_modules/@polkadot/api/base/Decorate.js:282:67)
    at decorated.hasSubscriptions.creator.iterKey.creator.meta.type.isMap.creator.meta.type.asMap.linked.isTrue.args (/Users/belsy/entropyRepo/m2-feedback-cli/node_modules/@polkadot/api/base/Decorate.js:286:24)
    at Object.eventTopics (/Users/belsy/entropyRepo/m2-feedback-cli/node_modules/@polkadot/api/promise/Api.js:78:14)
```

I am can add an arg before the hash and an empty array is returned, not sure what it should be as it is not documented. 

Thanks!

**Comment by jacogr** [comment]
Both the API for your chain and the docs are correct.

- the docs will always reflect the latest substrate master - that entry is not a simple map
- the API will decorate based on what your specific chain has, https://polkadot.js.org/api/start/basics.html#metadata, according to the types

So you are connecting to an older non-up-to-date chain, which has 2 arguments for an earlier generation. You will need to either -

- check the actual node code to see what it expects
- connect to the chain via the apps UI and look at the chain state (it decorates based on the chain metadata)

**Comment by whalelephant** [comment]
ah that was correct, I was on pre v2 node and v1.7.1 of polkadot.js 

I was able to check what the arguments needed were as suggested. Thanks!
