### ISSUE TITLE
Unable to run the sample code

### ISSUE THREAD

**Issue by ansonla3** [polkadot-js/api#2136]
Substrate latest commit :` 04276e749c40e6cd3de9c1f94e69b461b1e43d55 `

Tried PolkadotJS API Version:  `1.9.1` & `1.10.0-beta.7`

Code example: https://polkadot.js.org/api/examples/promise/06_make_transfer/

Error
```
node index.js 
2020-04-04 01:02:29        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature")): RuntimeApi("Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: No such 
Error: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature")): RuntimeApi("Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: No such 
    at RpcCoder.checkError (/Users/anson/test-transfer/node_modules/@polkadot/rpc-provider/coder/index.js:80:13)
    at RpcCoder.decodeResponse (/Users/anson/test-transfer/node_modules/@polkadot/rpc-provider/coder/index.js:45:10)
    at WsProvider.value (/Users/anson/test-transfer/node_modules/@polkadot/rpc-provider/ws/Provider.js:160:90)
    at W3CWebSocket.value [as onmessage] (/Users/anson/test-transfer/node_modules/@polkadot/rpc-provider/ws/Provider.js:140:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/anson/test-transfer/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/anson/test-transfer/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/anson/test-transfer/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:321:20)
    at WebSocketConnection.processFrame (/Users/anson/test-transfer/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/anson/test-transfer/node_modules/websocket/lib/WebSocketConnection.js:323:40
```

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain
