### ISSUE TITLE
Cannot run docs/examples/promise/06_make_transfer

### ISSUE THREAD

**Issue by saltduck** [polkadot-js/api#2190]
After execute yarn start, I got following error:
`2020-04-17 15:26:54        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature")): RuntimeApi("Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: No such
Error: 1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature")): RuntimeApi("Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: No such
    at RpcCoder._checkError (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/@polkadot/rpc-provider/coder/index.js:83:13)
    at RpcCoder.decodeResponse (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/@polkadot/rpc-provider/coder/index.js:46:10)
    at WsProvider.value (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/@polkadot/rpc-provider/ws/Provider.js:160:90)
    at W3CWebSocket.value [as onmessage] (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/@polkadot/rpc-provider/ws/Provider.js:140:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/mnt/c/Users/hongsn/code/my-benchmark/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /mnt/c/Users/hongsn/code/my-benchmark/node_modules/websocket/lib/WebSocketConnection.js:323:40`

Substrate version: 2.0.0-alpha.5

**Comment by jacogr** [comment]
https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

**Comment by clearloop** [comment]
> https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

https://polkadot.js.org/docs/api/FAQ#i-cannot-send-transactions-from-my-node-template-based-chain

Patch the new URL.
