### ISSUE TITLE
polkadot-types-from-chain cli doesn't work with ts definition file

### ISSUE THREAD

**Issue by xlc** [polkadot-js/api#2337]
With this command

```
polkadot-types-from-chain --endpoint ws://localhost:9944 --output ./packages/types/src/interfaces --package @acala-network/types/interfaces
```

Gives me this error

```
Generating from metadata, 148,228 bytes
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/Users/xiliangchen/projects/acala/acala.js/packages/types/src/interfaces/definitions'
Require stack:
- /Users/xiliangchen/projects/acala/acala.js/node_modules/@polkadot/typegen/fromChain.js
- /Users/xiliangchen/projects/acala/acala.js/node_modules/@polkadot/typegen/scripts/polkadot-types-from-chain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at generate (/Users/xiliangchen/projects/acala/acala.js/node_modules/@polkadot/typegen/fromChain.js:34:12)
    at W3CWebSocket.websocket.onmessage (/Users/xiliangchen/projects/acala/acala.js/node_modules/@polkadot/typegen/fromChain.js:94:9)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/xiliangchen/projects/acala/acala.js/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/xiliangchen/projects/acala/acala.js/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/xiliangchen/projects/acala/acala.js/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xiliangchen/projects/acala/acala.js/node_modules/@polkadot/typegen/fromChain.js',
    '/Users/xiliangchen/projects/acala/acala.js/node_modules/@polkadot/typegen/scripts/polkadot-types-from-chain.js'
  ]
}
```

`console.log("!!!", require.extensions)` gives

```
!!! [Object: null prototype] {
  '.js': [Function (anonymous)],
  '.json': [Function (anonymous)],
  '.node': [Function (anonymous)],
  '.handlebars': [Function: extension],
  '.hbs': [Function: extension]
}
```

so some work is needed to make it recognize ts file

**Comment by jacogr** [comment]
Yes, sadly this is why the example refers to using ts-node - https://polkadot.js.org/api/examples/promise/90_typegen/#packages

There are other ways to solve the same issue, e.g. but using babel registration. (Which is actually what generally is used in polkadot-js). It would be cleaner with less mental gymnastics if this followed a smiliar approach.

**Comment by jacogr** [comment]
Closing. We have been using babel/register for a while (alongside the move to cjs for the files, so it should be operational as logged, or rather as I commented here)
