### ISSUE TITLE
Invalid transaction error on transfer 

### ISSUE THREAD

**Issue by fgimenez** [polkadot-js/api#2343]
Running 1.18.1 and v0.8.6-1fc6e5f-x86_64-linux-gnu running on `--dev` with this code:
```
const transfer = api.tx.balances.transfer(recipentAddress, amount);
await transfer.signAndSend(senderKeyPair);                     
```
i get this error:
```
2020-06-10 11:57:57        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: {"Custom":2}
2020-06-10 11:57:57             DRR: Error: 1010: Invalid Transaction: {"Custom":2}
    at RpcCoder._checkError (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/@polkadot/rpc-provider/coder/index.js:83:13)
    at RpcCoder.decodeResponse (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/@polkadot/rpc-provider/coder/index.js:46:10)
    at WsProvider.value (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/@polkadot/rpc-provider/ws/Provider.js:166:90)
    at W3CWebSocket.value [as onmessage] (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/@polkadot/rpc-provider/ws/Provider.js:146:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.processFrame (/home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/fgimenez/workspace/w3f/polkadot-api-client-ts/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
Also connecting apps to a 0.8.6 node and trying to send balance from Alice to Bob, screenshot attached.
![Screenshot_2020-06-10_11-47-52](https://user-images.githubusercontent.com/70376/84254643-c8cea100-ab11-11ea-871a-8cf64da7f4fd.png)

**Comment by jacogr** [comment]
That is 100% correct. 

https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L659

The UI reports what the node gives it. `--dev` runs the Polkadot runtime.
