### ISSUE TITLE
1014: Priority is too low

### ISSUE THREAD

**Issue by Tore19** [polkadot-js/api#2491]
We are trying to submit more than 1,000  extrinsics.  But every time after submitting dozens or hundreds extrinsics, the following error will be reported. What may be the problem?

2020-08-18 07:08:54        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (158898839129 vs 158898839129): The transaction has too low priority to replace another transaction already in the pool.
2020-08-18 07:08:54             DRR: Error: 1014: Priority is too low: (158898839129 vs 158898839129): The transaction has too low priority to replace another transaction already in the pool.
    at RpcCoder._checkError (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/coder/index.js:85:13)
    at RpcCoder.decodeResponse (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/coder/index.js:48:10)
    at WsProvider.value (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/ws/Provider.js:212:90)
    at W3CWebSocket.value [as onmessage] (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/ws/Provider.js:192:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/stafi/stafi-tx/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/stafi/stafi-tx/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/stafi/stafi-tx/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/home/stafi/stafi-tx/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/stafi/stafi-tx/node_modules/websocket/lib/WebSocketConnection.js:323:40
2020-08-18 07:08:54        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1014: Priority is too low: (158898839129 vs 158898839129): The transaction has too low priority to replace another transaction already in the pool.
(node:5639) UnhandledPromiseRejectionWarning: Error: 1014: Priority is too low: (158898839129 vs 158898839129): The transaction has too low priority to replace another transaction already in the pool.
    at RpcCoder._checkError (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/coder/index.js:85:13)
    at RpcCoder.decodeResponse (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/coder/index.js:48:10)
    at WsProvider.value (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/ws/Provider.js:212:90)
    at W3CWebSocket.value [as onmessage] (/home/stafi/stafi-tx/node_modules/@polkadot/rpc-provider/ws/Provider.js:192:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/stafi/stafi-tx/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/stafi/stafi-tx/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/stafi/stafi-tx/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/home/stafi/stafi-tx/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/stafi/stafi-tx/node_modules/websocket/lib/WebSocketConnection.js:323:40

**Comment by Tore19** [comment]
Substrate 2.0.0-rc5
polkadot/api: 1.29.1
Call the funcitons like this:

const ex = this._.tx.sudo.sudo(this._.tx.claims.mintClaim(addr, amount));
this.blockFinalized(ex);

private blockFinalized(
        ex: SubmittableExtrinsic<"promise">,
        inFinialize?: boolean,
    ): Promise<ExResult> {
        const res = new ExResult(
            false,
            "", // blockHash
            "", // exHash
        );

        return new Promise((resolve, reject) => {
            ex.signAndSend(this.account, {}, (sr: SubmittableResult) => {
                const status = sr.status;
                const events = sr.events;

                log(`Transaction status: ${status.type}`);
                log(status.toString());

                if (status.isInBlock) {
                    res.blockHash = status.asInBlock.toHex().toString();
                    res.exHash = ex.hash.toHex().toString();
                    if (!inFinialize) {
                        res.isOk = true;
                        resolve(res);
                    }

                    if (events) {
                        events.forEach((value: EventRecord): void => {
                            log(
                                "\t" +
                                value.phase.toString() +
                                `: ${value.event.section}.${value.event.method}` +
                                value.event.data.toString(),
                            );

                            if (value.event.method.indexOf("Failed") > -1) {
                                res.isOk = false;
                                res.isErr = true;
                                reject(res);
                            }

                            if ((value.event.data[0] as DispatchError).isModule) {
                                res.docs = this._.registry.findMetaError(
                                    (value.event.data[0] as DispatchError).asModule.toU8a(),
                                );

                                reject(res);
                            }
                        });
                    }
                } else if (status.isInvalid) {
                    log.warn("Invalid Extrinsic");
                    reject(res);
                } else if (status.isRetracted) {
                    log.warn("Extrinsic Retracted");
                    reject(res);
                } else if (status.isUsurped) {
                    log.warn("Extrinsic Usupred");
                    reject(res);
                } else if (status.isFinalized) {
                    res.isOk = true;
                    log(`Finalized block hash: ${res.blockHash}`);
                    resolve(res);
                }
            });
        });
    }

**Comment by jacogr** [comment]
You are resubmitting with the same nonce. If you want to do bulk submissions, follow this pattern - https://polkadot.js.org/api/cookbook/tx.html#how-do-i-take-the-pending-tx-pool-into-account-in-my-nonce

**Comment by Tore19** [comment]
Thanks! Solved
