### ISSUE TITLE
Decoration errors

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/api#2612]
Hi,

Tested @polkadot/api v1.31.2 in PolkaStats backend, crawling Kusama full chain and got some errors I want to share:

```
const blockHash = await api.rpc.chain.getBlockHash(4061641);
blockEvents = await api.query.system.events.at(blockHash);

Error: createType(Vec<EventRecord>):: Vec length 960823552 exceeds 32768
    at o (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:69825)
    at t.default._formatStorageData (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:342495)
    at t.default._formatOutput (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:341740)
    at l (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:339890)
```

```
const blockHash = await api.rpc.chain.getBlockHash(4061636);
blockEvents = await api.query.system.events.at(blockHash);

Error: createType(Vec<EventRecord>):: Unable to create Enum via index 162, in ApplyExtrinsic, Finalization, Initialization
    at o (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:69825)
    at t.default._formatStorageData (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:342495)
    at t.default._formatOutput (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:341740)
    at l (https://polkadot.js.org/apps/polkadot.01.cde4c033.js:1:339890)
```

**NOTE:** Also can be reproduced with api v1.34.0-beta.3 at https://polkadot.js.org/apps/#/js

**Comment by jacogr** [comment]
Weird, both works via the apps UI explorer.

**Comment by mariopino** [comment]
Strange, I got the errors 1 hour ago in JS console using the same API version (v1.34.0-beta.3), but now there is no error! Closing it then ...
