### ISSUE TITLE
Error on fetching events

### ISSUE THREAD

**Issue by TheGoldenEye** [polkadot-js/api#2625]
Chain: Kusama

The following error occurs on the specVersion border 2022 -> 2023:
```
Unable to decode storage system.events: createType(Vec<EventRecord>):: Vec length 6684928 exceeds 32768
2020-09-18 18:31:55        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Vec length 6684928 exceeds 32768
Error: createType(Vec<EventRecord>):: Vec length 6684928 exceeds 32768
```

Hint: To reproduce the error it is necessary to query the events of a block with specVersion 2022 before

example:
```
...
const blocks: number[] = [3860280, 3860301];
  for (let i = 0, n = blocks.length; i < n; i++) {
    console.log(blocks[i]);
    const hash = await api.rpc.chain.getBlockHash(blocks[i]);
    await api.query.system.events.at(hash);
  }
```

output
```
polka-store: v1.0.1
Chain:       Kusama
Node:        Parity Polkadot v0.8.23-d327000-x86_64-linux-gnu
Provider:    wss://cc3-3.kusama.network
API:         @polkadot/api v1.33.1

Press "Ctrl+C" to cancel ...
3860280
3860301
Unable to decode storage system.events: createType(Vec<EventRecord>):: Vec length 6684928 exceeds 32768
2020-09-18 18:31:55        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(Vec<EventRecord>):: Vec length 6684928 exceeds 32768
Error: createType(Vec<EventRecord>):: Vec length 6684928 exceeds 32768
    at createTypeUnsafe (/share/data/_jens/src/coins/polkadot/polka-store/polka-store/node_modules/@polkadot/types/create/createType.js:69:11)
    at Rpc._formatStorageData (/share/data/_jens/src/coins/polkadot/polka-store/polka-store/node_modules/@polkadot/rpc-core/index.js:421:40)
    at Rpc._formatOutput (/share/data/_jens/src/coins/polkadot/polka-store/polka-store/node_modules/@polkadot/rpc-core/index.js:387:21)
    at callWithRegistry (/share/data/_jens/src/coins/polkadot/polka-store/polka-store/node_modules/@polkadot/rpc-core/index.js:249:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jacogr** [comment]
Update to the latest beta. (Issue will be in Monday's version, already fixed in master/beta)
