### ISSUE TITLE
Derived TypedArray constructor created an array which was too small

### ISSUE THREAD

**Issue by gregzaitsev** [polkadot-js/api#2877]
When reading a vector (contains a little over 100 u64 elements) from a smart contract, API throws the error below. Ping me if you need the contract code, binaries, and full JS code.

API version: 2.8.1

SC Method definition:
```
pub fn get(&self) -> Vec<u64>
```

JS Code:
```
async function readContract(api, sender) {
  const abi = new Abi(contractAbi);
  const contract = new ContractPromise(api, abi, config.contractAddress);

  const vec = await contract.query.get(sender.address, value, maxgas);
  console.log("Vector read. Length: ", vec.output.length);
}
```

Error:
```
2020-11-27 17:30:03        REGISTRY: TypeError: Derived TypedArray constructor created an array which was too small
    at Bytes.slice (<anonymous>)
    at compactFromU8a (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/util/compact/fromU8a.js:41:40)
    at Function.decodeVec (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/node_modules/@polkadot/types/codec/Vec.js:50:55)
    at new Vec (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/node_modules/@polkadot/types/codec/Vec.js:29:28)
    at new <anonymous> (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/node_modules/@polkadot/types/codec/Vec.js:58:9)
    at initType (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/node_modules/@polkadot/types/create/createType.js:68:12)
    at formatData (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/util.js:20:39)
    at MapSubscriber.project (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/base/Contract.js:177:81)
    at MapSubscriber._next (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/operators/map.js:49:35)
Error: createType(Vec<u64>):: Derived TypedArray constructor created an array which was too small
    at createTypeUnsafe (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/node_modules/@polkadot/types/create/createType.js:71:11)
    at formatData (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/util.js:20:39)
    at MapSubscriber.project (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/@polkadot/api-contract/base/Contract.js:177:81)
    at MapSubscriber._next (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/ReplaySubject.js:50:31)
    at ConnectableSubscriber.Subscriber._next (/home/greg/Development/src/polkadot/nft/smart_contracts/load_test_scripts/node_modules/rxjs/internal/Subscriber.js:89:26)
```

**Comment by jacogr** [comment]
Just attaching the ABI and WASM here will do the trick. Would love to take a look.

**Comment by gregzaitsev** [comment]
Sure! Call `bloat(100)` to populate the contract's returned vector with 100 values.

[loadtester.tar.gz](https://github.com/polkadot-js/api/files/5609250/loadtester.tar.gz)

**Comment by jacogr** [comment]
Thank you, will take a peek tomorrow.

**Comment by jacogr** [comment]
Will release a 2.8.2 with #2879 - a bit confused, the fix makes sense, is correct (compared to subarray), but honestly not 100% sure why it does work without in some cases. Either way, it is a long-hidden correction that weirdly pops up now.

**Comment by gregzaitsev** [comment]
The fix works, thank you!!!
