### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module 'worker_threads' for 3.0.1

### ISSUE THREAD

**Issue by x88** [polkadot-js/api#2963]
I have updated api to `3.0.1` version, and when I try to initialize connection, I've got error:

```bash
node main.js 
(node:21256) UnhandledPromiseRejectionWarning: Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/docker/polkadot-profit-transformer/streamer/node_modules/fflate/lib/node-worker.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:21256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Initialization as `fastify` plugin

```javascript
const { ApiPromise, WsProvider } = require('@polkadot/api')
const fastifyPlugin = require('fastify-plugin')

const { SUBSTRATE_URI } = require('../environment')

const polkadotConnector = async (server, options = {}) => {
  const wsProvider = new WsProvider(SUBSTRATE_URI)
  const api = await ApiPromise.create({ provider: wsProvider })
  server.decorate('polkadotConnector', api)
}

module.exports = fastifyPlugin(polkadotConnector)
```

**Comment by jacogr** [comment]
Not quite familiar with fastify at all. 

Having said that, will try and create a reproduction from the above.

**Comment by jacogr** [comment]
@x88 Could you please just update `fflate` to 0.4.3 - there has been a fix to the underlying library which should solve the issue.

**Comment by jacogr** [comment]
The 3.1 release (due today, otherwise first thing on Monday, EU-time) will have the require bumps on the libraries.
