### ISSUE TITLE
Fetching polkadot block #3337808 results in `failed decoding staking.submitElectionSolutionUnsigned ... Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by emostov** [polkadot-js/api#3055]
The below code
```typescript
import { ApiPromise, WsProvider } from '@polkadot/api';
async function main() {
	const provider = new WsProvider('wss://rpc.polkadot.io');
	const api = await ApiPromise.create({ provider });
	const hashBlock3337808 = await api.rpc.chain.getBlockHash(3337808);
	const { block: block3337808 } = await api.rpc.chain.getBlock(
		hashBlock3337808
	);
}
main().catch(console.log);
```
Results in this error
```
2021-01-14 13:57:24        REGISTRY: Error: Call: failed decoding staking.submitElectionSolutionUnsigned:: Struct: failed on args: {"winners":"Vec<ValidatorIndex>","compact":"CompactAssignments","score":"ElectionScore","era":"EraIndex","size":"ElectionSize"}:: Maximum call stack size exceeded
    at new GenericCall (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/generic/Call.js:147:13)
    at new Type (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/registry.js:311:16)
    at initType (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/registry.js:268:39)
    at Function.decodeExtrinsic (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:47:31)
    at new GenericExtrinsicV4 (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/extrinsic/v4/Extrinsic.js:30:27)
    at new Type (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/registry.js:311:16)
```

If I understand correctly, it looks like the election solution has a massive and fairly nested set of args, blowing the call stack at some point when they are being processed: 
https://polkascan.io/polkadot/inherent/3337808-1

My current fix is using the flag `node --stack_size=1300 my-server.js`. Do you think this is an ok solution to ship?

(rel: https://github.com/paritytech/substrate-api-sidecar/issues/389)

**Comment by jacogr** [comment]
So it depends on what the issue is -

- is a wrong type resulting in ruond-and-round, that needs a fix - so it depends on what the type was at that point in time (based on the runtime and changes)
- for the above, Polkascan may _also_ be wrong since they have actual alerts setup for type changes here

If the above is not applicable, probably need to look at optimization, wherever that may be.

Short term, if it does indeed decode correctly, as horrible as the above is, it is probably an option. (But non-sustainable)

**Comment by jacogr** [comment]
... ok, just checked, current runtime, current types, so it is an optimization problem.
