### ISSUE TITLE
Unable to resolve AssetID and Block Length 

### ISSUE THREAD

**Issue by ksr30** [polkadot-js/api#3087]
Hey everyone,
I am getting this error while using Polkadot-js api.
```
2021-01-21 16:23:59        REGISTRY: Unable to resolve type AssetID, it will fail on construction
2021-01-21 16:23:59        REGISTRY: Unable to resolve type BlockLength, it will fail on construction
2021-01-21 16:23:59        REGISTRY: Error: Cannot construct unknown type BlockLength
    at new DoNotConstruct (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/primitive/DoNotConstruct.js:21:11)
    at new <anonymous> (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/primitive/DoNotConstruct.js:27:9)
    at new Type (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/registry.js:318:16)
    at initType (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/registry.js:275:39)
    at /home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
    at Array.reduce (<anonymous>)
    at /home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
2021-01-21 16:23:59        API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockLength):: Cannot construct unknown type BlockLength
    at ApiPromise.value (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/api/base/Init.js:86:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9)
2021-01-21 16:23:59        API/INIT: Error: createType(BlockLength):: Cannot construct unknown type BlockLength
    at createTypeUnsafe (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/registry.js:275:39)
    at /home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
    at Array.reduce (<anonymous>)
    at /home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
    at Array.reduce (<anonymous>)
    at decorateConstants (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/metadata/decorate/constants/index.js:17:18)
    at extractProperties (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/registry.js:120:53)
    at TypeRegistry.setMetadata (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/types/create/registry.js:426:29)
(node:25658) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(BlockLength):: Cannot construct unknown type BlockLength
    at ApiPromise.value (/home/ubuntu/Polkadex/load-tester/node_modules/@polkadot/api/base/Init.js:86:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9)
(node:25658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by jacogr** [comment]
Substrate master? The PRs to both went in yesterday and was added to the API this morning. 

They are available in the latest beta versions.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/api/pull/3085
