### ISSUE TITLE
"Invalid decoded address length" exceptions, when validator has short address

### ISSUE THREAD

**Issue by x88** [polkadot-js/api#3109]
Sometimes queries responses `api.query.session.validators.at(blockHash)` or `.query.session.disabledValidators.at(blockHash)` returns validator entry with short address length (for Polkadot Live, `validator.toString()` returns  `13` value at `era = 2`) , throws exceptions, when validator value used as argument. 

What's specs or behaviors for process these addresses? 

````
2021-01-25 12:56:33        REGISTRY: Error: Decoding 14: Invalid decoded address length
    at assert (node_modules/@polkadot/util-crypto/node_modules/@polkadot/util/assert.js:34:11)
    at decodeAddress (node_modules/@polkadot/util-crypto/address/decode.js:36:20)
    at decodeAccountId (node_modules/@polkadot/types/generic/AccountId.js:26:42)
    at new GenericAccountId (node_modules/@polkadot/types/generic/AccountId.js:42:21)
    at new Type (node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (node_modules/@polkadot/types/create/registry.js:297:39)
    at createKeyDoubleMap (node_modules/@polkadot/metadata/decorate/storage/createFunction.js:73:25)
2021-01-26 04:56:33        REGISTRY: Error: createType(AccountId):: Decoding 14: Invalid decoded address length
    at createTypeUnsafe (node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (node_modules/@polkadot/types/create/registry.js:297:39)
    at createKeyDoubleMap (node_modules/@polkadot/metadata/decorate/storage/createFunction.js:73:25)
    at arg (node_modules/@polkadot/metadata/decorate/storage/createFunction.js:189:70)
    at decodeStorageKey (node_modules/@polkadot/types/primitive/StorageKey.js:72:12)
    at new StorageKey (node_modules/@polkadot/types/primitive/StorageKey.js:124:9)
    at initType (node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (node_modules/@polkadot/types/create/createType.js:69:12)
    at inputs.map (node_modules/@polkadot/rpc-core/index.js:375:70)
2021-01-25 12:56:33        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: createType(StorageKey):: createType(AccountId):: Decoding 14: Invalid decoded address length

```

**Comment by jacogr** [comment]
The AccountId in Polkadot is always 32 bytes. 

Do you have an example blockHash that is problematic? Would like to take a look.

**Comment by x88** [comment]
> The AccountId in Polkadot is always 32 bytes.
> 
> Do you have an example blockHash that is problematic? Would like to take a look.

Func `.query.session.disabledValidators.at(blockHash)` Era 1, blockHash: `0x1d3c2abe129e4e816daf24fc164b4e64f09e8254126f27a4e731a9b63dccba92`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 14: Invalid decoded address length".`

Func `.query.session.disabledValidators.at(blockHash)` Era 35, blockHash `0x7815685b785d2bb1c6c3d08618e6d0280a0e08209b5bdb592bec953ffd75ab82`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 121: Invalid decoded address length".`

Func `.query.session.disabledValidators.at(blockHash)` Era 45, blockHash `0x1391efbc1256cd58ce0f3ace7cffa04a3aea9bdc28c5d54f3d1d00cb703d03c4`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 117: Invalid decoded address length".`

Func `.query.session.disabledValidators.at(blockHash)` Era 50, blockHash `0xa660079e8a8b1028636d6fab2619e23f4cd692e711355d20d0f68895a8ed5a42`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 33: Invalid decoded address length".`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 48: Invalid decoded address length".`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 112: Invalid decoded address length".`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 119: Invalid decoded address length".`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 138: Invalid decoded address length".`
`Error: createType(StorageKey):: createType(AccountId):: Decoding 176: Invalid decoded address length".`

And sometimes again.

**Comment by jacogr** [comment]
Not sure why `disabledValidators` tries to decode at `AccountId` in the current Polkadot version it is `u32`.

**Comment by jacogr** [comment]
One additional question - which version of the API are you on?

**Comment by x88** [comment]
> One additional question - which version of the API are you on? The reason for asking is that I cannot replicate the first on the current release version of the API.

We tested on `3.2.1 - 3.6.1` versions
There is current [package.json](https://github.com/p2p-org/polkadot-profit-transformer/blob/master/streamer/package.json#L18), and there calling method [staking.js#231](https://github.com/p2p-org/polkadot-profit-transformer/blob/master/streamer/src/services/staking.js#L231)

**Comment by jacogr** [comment]
Ok, just be aware that `session.validators` & `session.disabledValidators` return 2 different results -

- validators - the actual AccountId
- disabledValidators - the index (u32) of the validator in the validators list

So here you treat the disabled array the same as the validator array - https://github.com/p2p-org/polkadot-profit-transformer/blob/master/streamer/src/services/staking.js#L257 (that will fail when you followed the disabled path)

**Comment by jacogr** [comment]
Here is the sample script I'm currently running from genesis - https://github.com/jacogr/sample-validators/blob/main/index.mjs#L20-L28 (including disabled -> validatorId mapping)
