### ISSUE TITLE
Trying to use @polkadot/types as a standalone library results in error

### ISSUE THREAD

**Issue by tomaka** [polkadot-js/api#3181]
I'm trying to use the `@polkadot/types` library in a stand-alone way.

I added `"@polkadot/types": "^3.9.3",` to my dependencies. But then, doing this:

```js
import { TypeRegistry } from '@polkadot/types';
```

Results in: (edited error)

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /home/pierre/Projets/smoldot/bin/events-export-parser/node_modules/@polkadot/types/package-info.json
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:102:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:231:31)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:58:21)
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:63:9) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

([relevant line](https://github.com/polkadot-js/api/blob/a9c9fb5769dec7ada8612d6068cf69de04aa15ed/packages/types/src/detectPackage.ts#L21))

I'm not a JavaScript expert, so I don't know if I need to do something special, or if it's simply not intended to be used in a standalone way.

**Comment by jacogr** [comment]
The file def does get published, e.g.

```
$ mkdir -p empty
$ cd empty
$ empty yarn init
...
$ yarn add @polkadot/types
yarn add v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
...
$ ls -al node_modules/@polkadot/types/package-info.json 
-rw-r--r--  1 jaco  staff  53 Feb 16 10:17 node_modules/@polkadot/types/package-info.json
```

**Comment by tomaka** [comment]
Ah sorry, I scrolled up too much on my terminal and copy-pasted the wrong error.

After doing a `yarn install` (which I had forgotten to do), I obtain the actual problem:

```js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /home/pierre/Projets/smoldot/bin/events-export-parser/node_modules/@polkadot/types/package-info.json
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:102:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:231:31)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:58:21)
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:63:9) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by jacogr** [comment]
Ahh, ok for node and esm you need to explicitly add a flag for node (the json imports in mjs is experimental). So basically -

`node --experimental-json-modules ./index.mjs`

(Weirdly Node didn't tell you that, I could have sworn it did it for me)

**Comment by tomaka** [comment]
Cool, that's working, thanks a lot!

**Comment by jacogr** [comment]
I've been meaning to remove this import since it is horrible, explicitly in this case. Will bump it up my list anyway and get it into the packages.
