### ISSUE TITLE
ERR_REQUIRE_ESM with new 4.0.1 version

### ISSUE THREAD

**Issue by wpank** [polkadot-js/api#3282]
After upgrading the 1kv-backend to v4.0.1, trying to run it will throw the following:

```
[1] internal/modules/cjs/loader.js:1080
[1]       throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
[1]       ^
[1] 
[1] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/will/dev/parity/1k-validators-be/node_modules/@polkadot/x-rxjs/index.js
[1] require() of ES modules is not supported.
[1] require() of /home/will/dev/parity/1k-validators-be/node_modules/@polkadot/x-rxjs/index.js from /home/will/dev/parity/1k-validators-be/node_modules/@polkadot/api/promise/index.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[1] Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/will/dev/parity/1k-validators-be/node_modules/@polkadot/x-rxjs/package.json.
[1] 
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1]     at Module.require (internal/modules/cjs/loader.js:952:19)
[1]     at require (internal/modules/cjs/helpers.js:88:18)
[1]     at Object.<anonymous> (/home/will/dev/parity/1k-validators-be/node_modules/@polkadot/api/promise/index.cjs:19:14)
[1]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
[1]   code: 'ERR_REQUIRE_ESM'
```

Not entirely sure how to solve this. Downgrading back to `3.11.1` and this works fine.

**Comment by jacogr** [comment]
Do you have a link to the code? This should not happen.

Which node version?

**Comment by jacogr** [comment]
Ok, can replicate. Swearing since apparently despite my days-long testing on the 4.0.0 betas I only ever used Node ESM `index.mjs` files to test the 4.0.1 version where this issue crept in. Will figure it out and make a patch.
