### ISSUE TITLE
@polkadot/api v4.x is not compatible with Node.js 10.x

### ISSUE THREAD

**Issue by TheGoldenEye** [polkadot-js/api#3309]
Unfortunately the last version of the api is no longer compatible with Node.js 10.x.
Ubuntu 20.04 (LTS) comes with Node.js v10.19, this does not work anymore.

I get the following error message when starting my program (not compiling):
```
.../polka-store/node_modules/@polkadot/api/index.js:3
import "./detectPackage.js";
       ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (.../polka-store/build/ApiHandler.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Tested with API v4.03
Node.js v10.x: failed
Node.js v12.x: ok

**Comment by jacogr** [comment]
Indeed. Sadly 2 months before the LTS period ends.
