### ISSUE TITLE
Cannot read property 'addressRaw' of undefined error

### ISSUE THREAD

**Issue by boohyung** [polkadot-js/api#3398]
Hi. I found the problem for sending the transaction in Polkadot. "cannot read property 'addressRaw' of undefined error. I think cause is address type check using keyring package. Please let me know how we resolve the problem.

Used SDK is here.
```javascript
    "@polkadot/api": "^3.11.1",
    "@polkadot/api-derive": "^3.11.1",
    "@polkadot/keyring": "^5.9.2",
    "@polkadot/metadata": "^3.11.1",
    "@polkadot/rpc-core": "^3.11.1",
    "@polkadot/rpc-provider": "^3.11.1",
    "@polkadot/types": "^3.11.1",
    "@polkadot/types-known": "^3.11.1",
    "@polkadot/util": "^5.9.2",
    "@polkadot/util-crypto": "^5.9.2"
```

**Comment by jacogr** [comment]
It would mean you are not passing a pair through to sign. However without code, I am guessing. It will access the addressRaw on the pair passed in.

**Comment by boohyung** [comment]
Short code of sending transaction is here.

```javascript
createRawTransaction(txParams: ITransaction): any {
    
    txParams.transfer = PolkadotSigner.api.tx.balances.transfer(txParams.to, this.convertUnit("to", txParams.amount))
    return txParams 
  
  }

  async signRawTransaction(txParams: any): Promise<any> {

    this.logger.debug('Raw Transaction:', txParams.transfer.toString()) 
    const nonce = await this.getNonce(txParams.from)
  
    const signedTx = await txParams.transfer.sign(this.wallet[txParams.from], { nonce })
    this.logger.debug('Signed Transaction:', signedTx.toString())

    await txParams.transfer.send()

    return signedTx
    
  }
  
  async sendRawTransaction(signedTx): Promise<string> {

    const buffer = Buffer.from(signedTx.hash)
    return `0x${buffer.toString('hex')}` // res
  }

```

**Comment by jacogr** [comment]
Where does the error occur?

**Comment by boohyung** [comment]
I don't know where dose the error occur. but do you know why this happens?

**Comment by jacogr** [comment]
What I mean is - on which line of code does it throw?

`addressRaw` is used on the pair being passed in to sign the message. Which mean that is that is undefined, you pass through `<undefined>.addressRaw`. 

https://github.com/polkadot-js/api/blob/a1f07e32743eed1c27bf06ca6fb9118afdbfa839/packages/types/src/extrinsic/v4/ExtrinsicSignature.ts#L158

**Comment by boohyung** [comment]
Thanks to your support @jacogr . Your comment has given me to fix the bug. 

BTW, Does @polkadot-sdk have a node dependency? I applied the latest SDK. but I found the index.js error. 

used SDK:
```bash
    "@polkadot/api": "^4.5.1",
    "@polkadot/keyring": "^6.1.1",
    "@polkadot/types": "^4.5.1",
    "@polkadot/metadata": "^4.5.1",
    "@polkadot/util": "^6.1.1",
    "@polkadot/util-crypto": "^6.1.1",
```

error: 
```bash
/home/polkadot/share/generic-signer/node_modules/@polkadot/api/index.js:3
import "./detectPackage.js";
       ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/polkadot/share/generic-signer/build/signers/Polkadot.js:37:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/polkadot/share/generic-signer/build/signers/SignerFactory.js:9:36)
```

**Comment by jacogr** [comment]
Use Node 12.x at least. 10.x does not support export maps and the LTS expires now.

**Comment by boohyung** [comment]
Thanks. I'm using Node 12.12.0 and working well.

**Comment by boohyung** [comment]
Now I'm using Node 14.x (LTS). And working well. Thanks for your support @jacogr
