### ISSUE TITLE
no such file or directory, open 'docs/substrate/storage-known-section.json'

### ISSUE THREAD

**Issue by yuhui1208** [polkadot-js/api#3416]
when i try to run this command `yarn  docs:metadata`, it throw out the follwoing error messages. How can I get this file? I cannot find this file under the docs path.
```
internal/fs/utils.js:308
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'docs/substrate/storage-known-section.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at addStorage (E:\code\polkadot-api\packages\typegen\src\/metadataMd.ts:204:43)
    at main (E:\code\polkadot-api\packages\typegen\src\/metadataMd.ts:313:42)
    at Object.<anonymous> (E:\code\polkadot-api\packages\typegen\scripts\polkadot-types-internal-metadata.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'docs/substrate/storage-known-section.json'
}
```

**Comment by jacogr** [comment]
https://github.com/polkadot-js/docs/blob/master/docs/substrate/storage-known-section.json

**Comment by yuhui1208** [comment]
ok, thanks, I copied this file from the docs to the relative folder and solved the problem
