### ISSUE TITLE
is there any way to silence the logger in test env

### ISSUE THREAD

**Issue by woss** [polkadot-js/api#3428]
in test env i'm getting a lot of useless 'errors' when I disconnect from the test chain. 
```
021-04-22 22:13:40        RPC-CORE: subscribeStorage(keys?: Vec<StorageKey>): StorageChangeSet:: disconnected from ws://127.0.0.1:9944: 1000:: Normal connection closure
2021-04-22 22:13:40             DRR: Error: disconnected from ws://127.0.0.1:9944: 1000:: Normal connection closure
    at W3CWebSocket.value [as onclose] (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/@polkadot+rpc-provider@4.6.2/node_modules/@polkadot/rpc-provider/ws/index.cjs:176:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:369:20)
    at WebSocketConnection.handleSocketClose (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (node:events:369:20)
    at TCP.<anonymous> (node:net:666:12)
2021-04-22 22:13:40        API/INIT: Error: disconnected from ws://127.0.0.1:9944: 1000:: Normal connection closure
    at W3CWebSocket.value [as onclose] (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/@polkadot+rpc-provider@4.6.2/node_modules/@polkadot/rpc-provider/ws/index.cjs:176:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/yaeti@0.0.6/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:369:20)
    at WebSocketConnection.handleSocketClose (/home/daniel/projects/anagolay/js-sdk/node_modules/.pnpm/websocket@1.0.34/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (node:events:369:20)
    at TCP.<anonymous> (node:net:666:12)
2021-04-22 22:13:40        RPC-CORE: subscribeStorage(keys?: Vec<StorageKey>): StorageChangeSet:: disconnected from ws://127.0.0.1:9944: 1000:: Normal connection closure

```
i see there is now a new logger but can it be disabled for test env and how?
thanks

**Comment by jacogr** [comment]
The DEBUG="..." flags only affect debug output, not logging output. So it cannot be toggled.

**Comment by woss** [comment]
i can't find a trace of `DEBUG` in the code `❯ ag -G '\.ts$' DEBUG` yields nothing. 

also is it normal that it throws this error which is obviously not an error?

**Comment by jacogr** [comment]
1. https://github.com/polkadot-js/common/blob/master/packages/util/src/logger.ts#L85
2. It is an error - the connect was interrupted without the subscription being cancelled (the fact that it, e.g. in the case of `RuntimeVersion` is not a user-subscription, but rather an API subscription doesn't make it less of an error)

**Comment by woss** [comment]
1. oh so it is in the common. my bad
2. if not `api.disconnect()` then how to properly disconnect and cancel any runtime subscriptions?

**Comment by jacogr** [comment]
The API itself does not cancel any internal subscriptions on manual disconnect since it doesn't track it, it is possible with some intertwining, but never bubbled anywhere close to the top of things to do since there is no real benefit (apart from silencing logs on manual disconnects). 

As mentioned above, the fact that is doesn't do it, doesn't make it "correct", it is still something that should be done "at some point down the line". (Since the providers manage re-connections and subscriptions, it picks up where it left off on re-connection, so explicitly breaking also has some other effects for additional tracking that should be done internally). The long and the short of it - doable, but not pretty, but "someday".

For user subs, just call unsubscribe on the promise returned from the sub.

**Comment by woss** [comment]
ok, thanks for the explanation, i'm already calling unsub when i do other stuff like saving to the chain. this was mainly in the test env since i couldn't figure out how to mock the API, which would be super awesome if i could. I saw the there are some mocks in the rpc-provider but never could make it work in my test env that's why i decided to spin the test chain and test it there. If you have any idea how to mock the api inside from inside the tests i believe it would help the community to test custom sdks built on top of this one (like mine)

**Comment by jacogr** [comment]
I added something in an unrelated cleanups PR in https://github.com/polkadot-js/api/pull/3441/files#diff-90f73ef31127f89217ef376346dfd889d072bb95dcc2742bd32a65c4c9566b10R53, which may silence the API, untested as to if it does all the unsubs.

PRs welcome if there are additional.
