### ISSUE TITLE
Error: createType(Text):: Text:: Decoded input doesn't match input

### ISSUE THREAD

**Issue by SaberDoTcodeR** [polkadot-js/api#3515]
Hi, I call my smart contract functions and they return correctly but when I call one specific function in polkadot.js, this error happens:
```
Error: createType(Text):: Text:: Decoded input doesn't match input, received 0x2070726f7669646572 (9 bytes), created 0x242070726f7669646572 (10 bytes)
    at createTypeUnsafe (node_modules/@polkadot/types/create/createType.cjs:58:11)
    at formatData (node_modules/@polkadot/api-contract/util.cjs:20:39)
    at MapSubscriber.project (node_modules/@polkadot/api-contract/base/Contract.cjs:162:81)
    at MapSubscriber._next (node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (node_modules/rxjs/internal/Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (node_modules/rxjs/internal/ReplaySubject.js:50:31)
    at ConnectableSubscriber.Subscriber._next (node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/project/node_modules/@polkadot/rpc-core/index.cjs:262:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The function in ink! contract
```
 pub fn get_username(&self) -> String {
            let caller: AccountId = self.env().caller();
            match self.address_to_username.get(&caller) {
                Some(username) => username.clone(),
                None => panic!("this address has not a valid associated username!"),
            }
}
```

I use these versions:
```
 "@polkadot/api": "^4.9.2",
 "@polkadot/api-contract": "^4.9.2",
```

Thanks for helping:)

**Comment by SaberDoTcodeR** [comment]
Hi @jacogr , Thanks for your response. I checked the latest version (4.9.3-16) and it still gives me an error with a slight different:
```
Error: createType(Text):: Text:: Decoded input doesn't match input, received 0x2070726f7669646572 (9 bytes), created 0x242070726f7669646572 (10 bytes)
    at createTypeUnsafe (node_modules/@polkadot/types/create/createType.cjs:58:11)
    at MapSubscriber.project (node_modules/@polkadot/api-contract/base/Contract.cjs:130:85)
    at MapSubscriber._next (node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (node_modules/rxjs/internal/Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (node_modules/rxjs/internal/ReplaySubject.js:50:31)
    at ConnectableSubscriber.Subscriber._next (node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/saber/Documents/GitHub/SubsCrypt-npm-library/node_modules/@polkadot/rpc-core/index.cjs:254:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jacogr** [comment]
Ummm... Could you please share the `.contract` file to enable me to take a look? (Or the ABI + WASM, the first is just a nice bundle of both)

**Comment by jacogr** [comment]
Since you tries the betas... can you give `4.9.3-17` a go since it includes the linked PR? 

(There was a case that was missed, it has been added alongside the missing tests for these checks...)

**Comment by SaberDoTcodeR** [comment]
Thanks a lot, in the `4.9.3-17` version it is solved.

**Comment by jacogr** [comment]
Excellent, thanks for the beta bug report here. It will be in the minor release on Monday.

**Comment by SaberDoTcodeR** [comment]
@jacogr Sorry to bother again, but I have a problem with the output, it should be for example something like `user` but it's a string like this `\x10user`.
Or another example is that it should return `povider` but it returns it with extra space at the beginning of string " provider".
It looks like the `result.output.toHuman()` returns string with additional char at the begining.

**Comment by jacogr** [comment]
The ` provider` is indeed how the data is on-chain... the hex data actually shows that.

Will check `toHuman()` is should return without the extra `\x10`

**Comment by SaberDoTcodeR** [comment]
This is the [contract file](https://github.com/oxydev/SubsCrypt-ink/releases/download/0.2/subscrypt.contract).

**Comment by jacogr** [comment]
Probably my machine, cannot quite get it working on the lastest Substrate master, it traps no matter what I do.

**Comment by SaberDoTcodeR** [comment]
do you want to access my canvas local node which has an active contract? please share with me your ssh public key via my email and then run this command so you can access it in your localhost:
```
ssh -fNT root@206.189.154.160 -L localhost:8000:localhost:8000 -L localhost:9615:localhost:9615 -L localhost:9944:localhost:9944
```
my email: 
szafarpoor@ce.sharif.edu

**Comment by azhu003** [comment]
Hi, did you solve this problem, I also encountered a similar problem
![image](https://user-images.githubusercontent.com/29949867/119809989-32f57700-bf18-11eb-96fa-332fb64ed40f.png)

**Comment by jacogr** [comment]
@azhu003 Your issue have got nothing to do with the decoding of `Text` fields and it out of scope for this as logged. Rather your contract pallet version is different from the one the API supports - it only tracks latest Substrate master for contracts since it evolves constantly. 

@SaberDoTcodeR Could you please verify if it is still an issue in 4.11.2?
