### ISSUE TITLE
Failed to decode Kusama block #7487667

### ISSUE THREAD

**Issue by emostov** [polkadot-js/api#3535]
Running with @polkadot/api@4.9.3-23

```javascript
	const api = await ApiPromise.create({
		provider: new WsProvider('wss://kusama.api.onfinality.io/public-ws'),
	});

	const blockHash7487667 = await api.rpc.chain.getBlockHash(7487667);
	const block7487667 = await api.rpc.chain.getBlock(blockHash7487667);
```

Results in 

```bash
2021-05-15 23:52:27             VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
2021-05-15 23:52:27        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
    at createTypeUnsafe (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/createType.cjs:55:11)
    at RpcCore._formatOutput (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/rpc-core/index.cjs:381:41)
    at callWithRegistry (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/rpc-core/index.cjs:247:42)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

(`electionprovidermultiphase.submitUnsigned` extrinsic on subscan: https://kusama.subscan.io/extrinsic/7487667-2)

**Comment by emostov** [comment]
The issue is also reproducible on Kusama block #7491223

**Comment by jacogr** [comment]
Honestly don’t know. Looked at those types this week and they seemed sane compare to Substarte.  So another pair of eyes appreciated. 

Will take a look later again.

**Comment by jacogr** [comment]
@arjanz Figured it out... it is related to the bump to 24 nominators, there are not 8 extra entries in the struct.
