### ISSUE TITLE
RPC methods not decorated & Unable to query dispatch info ... etc. ERRORS!!

### ISSUE THREAD

**Issue by gitloverr** [polkadot-js/api#3575]
hi everyone,

after upgrading to node 0.9.3 version, when I try to send dot to an account, I got those errors, what happed? how do I fix those?

```
2021-05-27 17:33:44        API/INIT: RPC methods not decorated: state_getChildReadProof, state_traceBlock, system_reservedPeers
2021-05-27 17:28:00        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 1: Unable to query dispatch info.: Application, Execution, Other, Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x232c - <unknown>!rust_begin_unwind\n    1: 0x2079 - <unknown>!core::panicking::panic_fmt::h04ce70065a809fb8\n    2: 0x18897b - <unknown>!Transaction…
(node:20585) UnhandledPromiseRejectionWarning: Error: 1: Unable to query dispatch info.: Application, Execution, Other, Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x232c - <unknown>!rust_begin_unwind\n    1: 0x2079 - <unknown>!core::panicking::panic_fmt::h04ce70065a809fb8\n    2: 0x18897b - <unknown>!Transaction…
    at RpcCoder._checkError (/usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at WsProvider.value (/usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/rpc-provider/ws/index.cjs:231:90)
    at W3CWebSocket.value [as onmessage] (/usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/rpc-provider/ws/index.cjs:211:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/share/nginx/html/cryptonodeapi/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/x-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/x-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/x-ws/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/share/nginx/html/cryptonodeapi/node_modules/@polkadot/x-ws/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:75:11)


Polkadot- js-Api versions: 
"@polkadot/api": "^4.7.2",
    "@polkadot/keyring": "^6.3.1",
    "@polkadot/types": "^4.7.2",
    "@polkadot/util": "^6.3.1",
    "@polkadot/util-crypto": "^6.3.1",



```

thank you

**Comment by jacogr** [comment]
You are on an old version of the API with these - `RPC methods not decorated: state_getChildReadProof, state_traceBlock, system_reservedPeers`

- 4.11.1 introduced `state_getChildReadProof` https://github.com/polkadot-js/api/releases/tag/v4.11.1
- 4.9.1 introduced `state_traceBlock` & `system_reservedPeers` https://github.com/polkadot-js/api/releases/tag/v4.9.1

With the pending 9030 runtime upgrade, the older versions won't be able to connect anymore since the metadata format has been changed in the runtime.

**Comment by gitloverr** [comment]
thank you solved after upgrade the packages..
