### ISSUE TITLE
plasm - REGISTRY: Unable to resolve type SmartContract

### ISSUE THREAD

**Issue by VadneyK** [polkadot-js/api#3588]
Hello I am trying to connect to a local [ plasm node instance](https://github.com/PlasmNetwork/Plasm/tree/dusty) with polkadot/api

I posted the node side error message here:
https://github.com/PlasmNetwork/Plasm/issues/303
I have the node running on `127.0.0.1:9944` as selected.
It was just working, but the second time I ran the code I got the error below

here is my config:
MacOS BigSur 11.2.3 M1 chip

<img width="289" alt="Screen Shot 2021-05-29 at 7 13 53 PM" src="https://user-images.githubusercontent.com/57117207/120089746-037a7200-c0b2-11eb-94fe-899b386d9c64.png">

code:
<img width="1232" alt="Screen Shot 2021-05-29 at 7 13 13 PM" src="https://user-images.githubusercontent.com/57117207/120089742-ecd41b00-c0b1-11eb-902b-42aba67b21da.png">

error message:
kentarovadney@Kentaros-MacBook-Air polkadot-practice % node index.js
2021-05-29 19:09:16        REGISTRY: Unable to resolve type SmartContract, it will fail on construction
2021-05-29 19:09:16        METADATA: Unknown types found, no types for SmartContract
2021-05-29 19:09:16        API/INIT: Error: FATAL: Unable to initialize the API: createType(SmartContract):: Cannot construct unknown type SmartContract
    at EventEmitter.value (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/api/base/Init.js:70:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
2021-05-29 19:09:16        API/INIT: Error: createType(SmartContract):: Cannot construct unknown type SmartContract
    at createTypeUnsafe (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/types/create/createType.js:46:11)
    at createType (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/types/create/createType.js:57:10)
    at TypeRegistry.createType (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/types/create/registry.js:284:12)
    at extendHeadMeta (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:87:53)
    at extendPrefixedMap (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:110:23)
    at createFunction (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:146:5)
    at file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/metadata/decorate/storage/index.js:32:45
    at Array.reduce (<anonymous>)
    at file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/metadata/decorate/storage/index.js:30:39
    at Array.reduce (<anonymous>)

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/start/types.extend

The chain you are connecting to defines custom types, the developer needs to let the API know how they look.

**Comment by VadneyK** [comment]
thanks!
