### ISSUE TITLE
State for a range of blocks - tutorial

### ISSUE THREAD

**Issue by VadneyK** [polkadot-js/api#3593]
I'm following the [tutorial here](https://polkadot.js.org/docs/api/start/api.query.other#state-for-a-range-of-blocks) to go through the information, but I am running into the error attatched below. Is the tutorial for some older version of the api, not the current up to date one?

`kentarovadney@Kentaros-MacBook-Air polkadot-practice % node query.js
file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/util/assert.js:24
    throw new Error(isFunction(message) ? message() : message);
          ^

Error: Call to system.account needs 1 arguments, found []
    at assert (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/util/assert.js:24:11)
    at createKey (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:27:3)
    at file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:130:185
    at Function.decorated.key (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/api/base/Decorate.js:356:62)
    at ApiPromise._decorateStorageRange (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/api/base/Decorate.js:399:56)
    at file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/api/base/Decorate.js:360:63
    at file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/api/promise/index.js:59:26
    at new Promise (<anonymous>)
    at decorateCall (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/api/promise/index.js:55:10)
    at Function.range (file:///Users/kentarovadney/Desktop/code/polkadot-practice/node_modules/@polkadot/api/promise/index.js:87:73)
kentarovadney@Kentaros-MacBook-Air polkadot-practice % `

here is my code:

`// Import
import { ApiPromise, WsProvider } from "@polkadot/api";

// Construct
const wsProvider = new WsProvider("wss://rpc.polkadot.io");
const api = await ApiPromise.create({ provider: wsProvider });
await api.isReady;

// Do something
const ADDR = "5DTestUPts3kjeXSTMyerHihn1uwMfLj8vU8sqF7qYrFabHE";
const now = await api.query.timestamp.now();
const lastHdr = await api.rpc.chain.getHeader();
const startHdr = await api.rpc.chain.getBlockHash(
  lastHdr.number.unwrap().subn(500)
);

// retrieve the range of changes
const changes = await api.query.system.account.range([startHdr]);

changes.forEach(([hash, value]) => {
  console.log(hash.toHex(), value.toHuman());
});`

**Comment by jacogr** [comment]
You need to pass the specific account you want to retrieve over that range -

```js
const ADDRESS = '....'; // ss58 address goes here

api.query.system.account.range([startHdr], ADDRESS);
```

Bear in mind that `.range` is deprecated and will be removed. (Since it is an unsafe RPC, not exposed by default)

**Comment by VadneyK** [comment]
thanks!
