### ISSUE TITLE
ApiPromise.create will not reject promise even with throwOnConnect when node is down

### ISSUE THREAD

**Issue by lucasrcosta** [polkadot-js/api#3603]
I expected `await ApiPromise.create({ provider: wsProvider, throwOnConnect: true })` to throw an error when it can't connect to the RPC (so I can try another node, or recover in another way).

I'm running on NodeJS 14 and `"@polkadot/api": "4.12.1"`.
```
process.on('uncaughtException', console.error)
process.on('unhandledRejection', console.error)

const wsProvider = new WsProvider(endpoint, undefined, headers)
wsProvider.on('error', console.error)

try {
  const api = await ApiPromise.create({ provider: wsProvider, throwOnConnect: true })
} catch(error) {
  console.log('=== THIS LINE NEVER RUNS ===')
  console.log(error)
}
```
Here I'm already using a few proposed solutions from other issues.

Error log:

```
2021-06-01 15:26:18        RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Instantiation, \"Instantiation: Export ext_logging_max_level_version_1 not found\
2021-06-01 15:26:18        API/INIT: Error: FATAL: Unable to initialize the API: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Instantiation, \"Instantiation: Export ext_logging_max_level_version_1 not found\
    at EventEmitter.value (/Users/lucasrcosta/Crypto/backend/node_modules/@polkadot/api/base/Init.cjs:88:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-06-01 22:26:18.794 Error: FATAL: Unable to initialize the API: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Instantiation, \"Instantiation: Export ext_logging_max_level_version_1 not found\
    at EventEmitter.value (/Users/lucasrcosta/Crypto/backend/node_modules/@polkadot/api/base/Init.cjs:88:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

2021-06-01 15:26:18        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Instantiation, \"Instantiation: Export ext_logging_max_level_version_1 not found\
2021-06-01 15:27:18          API-WS: disconnected from wss://[REDACTED]/ws: 1006:: Connection dropped by remote peer.
2021-06-01 15:27:22        RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Instantiation, \"Instantiation: Export ext_logging_max_level_version_1 not found\
2021-06-01 15:27:22        API/INIT: Error: FATAL: Unable to initialize the API: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Instantiation, \"Instantiation: Export ext_logging_max_level_version_1 not found\
    at EventEmitter.value (/Users/lucasrcosta/Crypto/backend/node_modules/@polkadot/api/base/Init.cjs:88:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-06-01 15:27:22        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: -32603: Unknown error occurred: Client, Application, VersionInvalid, RuntimeConstruction, Instantiation, \"Instantiation: Export ext_logging_max_level_version_1 not found\
```

**Comment by lucasrcosta** [comment]
Seems like the same issue as https://github.com/polkadot-js/api/issues/3392, but it seems not to have been solved by https://github.com/polkadot-js/api/pull/3395.

**Comment by lucasrcosta** [comment]
It worked. My bad... 🤷🏼
