### ISSUE TITLE
Is it possible to run under Node.js that version < 12 ?

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#3610]
We have a project that requires nodejs version no large than 12.  

If add Polka js api to project and run, I got error as expected.

But it is there any solution to run with  nodejs version < 12

Demo code:
```
const { ApiPromise, WsProvider } = require('@polkadot/api');
const { Keyring } = require('@polkadot/keyring');

const BOB = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty';

const TEST_NET = 'wss://westend-rpc.polkadot.io'
const RPC_URL = TEST_NET

async function main () {
  const provider = new WsProvider(RPC_URL);
  const api = await ApiPromise.create({ provider: provider });
  const keyring = new Keyring({ type: 'sr25519' });
  const alice = keyring.addFromUri('//Alice');

  const transfer = api.tx.balances.transfer(BOB, 12345);
  const hash = await transfer.signAndSend(alice);
  console.log('Transfer sent with hash', hash.toHex());
}

main().catch(console.error).finally(() => process.exit());
```

```
[18:09:08] root@iZm5e9ftqv2b81m28bhe2iZ /opt/programming/nodeJs/polka_demo/listent_new_block #node ./simple_transfer.js
/opt/programming/nodeJs/polka_demo/listent_new_block/node_modules/@polkadot/api/index.js:3
import "./detectPackage.js";
       ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/programming/nodeJs/polka_demo/listent_new_block/simple_transfer.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[18:09:20] root@iZm5e9ftqv2b81m28bhe2iZ /opt/programming/nodeJs/polka_demo/listent_new_block #

[18:09:20] root@iZm5e9ftqv2b81m28bhe2iZ /opt/programming/nodeJs/polka_demo/listent_new_block #node -v
v10.23.0      # CURRENT  ENV NODE VERSION
```

**Comment by jacogr** [comment]
API versions < 4.0 is still usable on < Node 12.

**Comment by code-brewer** [comment]
My demo project use bellowing libs run well under Node 12 and Node 14. 

>"@polkadot/api": "^4.12.1",
"@polkadot/keyring": "^6.6.1"

While looking for a solution, I think it is of little chance to use polka API under nodejs < v12.

Also, I reluctant to use old version APIs, because I think we must use the latest polka API, for many reasons. For example,  issue posted on #3500 in order to parse extrinsics when scanning the chain.
