### ISSUE TITLE
 Invalid Transaction: Transaction is outdated

### ISSUE THREAD

**Issue by past2017** [polkadot-js/api#3613]
we use api version v4.12.1 and polkadot node 0.9.2, when sendtransaction, error is reported as below,please help to check what happen, thanks

```
2021-06-02 16:21:00        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction is outdated
[2021-06-02T16:21:00.136] [ERROR] DOT - Error: 1010: Invalid Transaction: Transaction is outdated
    at RpcCoder._checkError (/root/chains-node-middleware/node-dot/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/root/chains-node-middleware/node-dot/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at WsProvider.value (/root/chains-node-middleware/node-dot/node_modules/@polkadot/rpc-provider/ws/index.cjs:239:90)
    at W3CWebSocket.value [as onmessage] (/root/chains-node-middleware/node-dot/node_modules/@polkadot/rpc-provider/ws/index.cjs:219:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/chains-node-middleware/node-dot/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/root/chains-node-middleware/node-dot/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/root/chains-node-middleware/node-dot/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:376:20)
    at WebSocketConnection.processFrame (/root/chains-node-middleware/node-dot/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /root/chains-node-middleware/node-dot/node_modules/websocket/lib/WebSocketConnection.js:323:40

```

**Comment by jacogr** [comment]
See the tx pool logic, quite possibly the nonce is old -

https://github.com/paritytech/substrate/blob/25388397aab20a24e2be55103dda95011aa04d7c/primitives/runtime/src/transaction_validity.rs#L44-L45

https://github.com/paritytech/substrate/blob/25388397aab20a24e2be55103dda95011aa04d7c/primitives/runtime/src/transaction_validity.rs#L98
