### ISSUE TITLE
api.rpc.payment.queryFeeDetails query fails at certain blocks in Kusama

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/api#3681]
I noticed that `api.rpc.payment.queryFeeDetails` query fails at certain blocks while `api.rpc.payment.queryInfo` works ok.

Example code:

```javascript
const blockNumber = 5935949;
const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
const { block } = await api.rpc.chain.getBlock(blockHash);
for (const extrinsic of block.extrinsics) {
  if (extrinsic.isSigned) {
    const queryFeeDetails= await api.rpc.payment.queryFeeDetails(extrinsic.toHex(), blockHash).catch(error => console.log(error)) || '';
    const queryInfo = await api.rpc.payment.queryInfo(extrinsic.toHex(), blockHash).catch(error => console.log(error)) || '';
    console.log('queryFeeDetails:', JSON.stringify(queryFeeDetails));
    console.log('queryInfo:', JSON.stringify(queryInfo));
  }
}
```

Output:

```
Error: 1: Unable to query fee details.: Application, Execution, Other, Exported method TransactionPaymentApi_query_fee_details is not found
    at b._checkError (https://polkadot.js.org/apps/polkadot.01.66a44011.js:1:136725)
    at b.decodeResponse (https://polkadot.js.org/apps/polkadot.01.66a44011.js:1:136344)
    at $.value (https://polkadot.js.org/apps/polkadot.01.66a44011.js:1:140850)
    at WebSocket.value (https://polkadot.js.org/apps/polkadot.01.66a44011.js:1:140663)
queryFeeDetails: ""
queryInfo: {"weight":216625000,"class":"Normal","partialFee":2599999026}
```

Tested in https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/js using:

Parity Polkadot v0.9.3
api v4.15.1
apps v0.93.2-24

**Comment by jacogr** [comment]
It gets thrown from the node itself.

**Comment by mariopino** [comment]
Thanks @jacogr, closing then
