### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by mmick66** [polkadot-js/api#3772]
I am trying to add tests using Jest and I get an error like so :

```
● Test suite failed to run

Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

By default "node_modules" folder is ignored by transformers.

Here's what you can do:
 • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

Details:

/Users/michaelmichailidis/Projects/polkadot-microservice/node_modules/@polkadot/api/index.js:3
import "./detectPackage.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module

  1 | import { Injectable } from '@nestjs/common';
> 2 | import { ApiPromise } from '@polkadot/api';
    | ^
  3 | import { Keyring, decodeAddress, encodeAddress } from '@polkadot/keyring';
  4 | import { KeyringPair } from '@polkadot/keyring/types';
  5 | import { hexToU8a, isHex, BN_HUNDRED, BN_ZERO, BN_MAX_INTEGER } from '@polkadot/util';

  at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
  at Object.<anonymous> (src/polkadot/polkadot.service.ts:2:1)
```

What is happening? How can I resolve this?

**Comment by branciard** [comment]
More information here #3430. I also try to fix my Jest tests after upgrade. I have not yet succeeded.

**Comment by Goldenteamway** [comment]
I have the same problem，how to configure jest?
