### ISSUE TITLE
Storage Decoding error when querying `system.account.at()` from a historic block

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#3871]
Resproducible Example:

```javascript
const { ApiPromise, WsProvider } = require('@polkadot/api');

const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://kusama-rpc.polkadot.io'),
    });
    
    const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';
    
    // Block Height 467568
    const historicBlockHash = '0x3361f6446c72aaa6679aa40a03e493a851161fd08cb53237968a9967902691c0'
    const { data: { free } } = await api.query.system.account.at(historicBlockHash, ALICE);

    console.log('Alice has a free balance of ', free.toHuman());
}
```

Resulting error:

```
RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","refcount":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)
Error: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","refcount":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)
    at RpcCore._newType (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)
    at RpcCore._formatStorageData (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/rpc-core/bundle.cjs:399:17)
    at RpcCore._formatOutput (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/rpc-core/bundle.cjs:376:19)
    at callWithRegistry (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/rpc-core/bundle.cjs:255:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

Using `@polkadot/api 5.4.1`

Rel: [#634](https://github.com/paritytech/substrate-api-sidecar/issues/634)

Per the related issue:

> this breakage may have something to do with a change of the storage key location for balances or account info.

**Comment by jacogr** [comment]
There is pre introduction of system.account - so whatever it returns won't be decodable.

```js
const a = await api.at('0x3361f6446c72aaa6679aa40a03e493a851161fd08cb53237968a9967902691c0');

console.log(Object.keys(a.query.system));
```

Rather at this point it is a balances.freeBalance query -

```js
const a = await api.at('0x3361f6446c72aaa6679aa40a03e493a851161fd08cb53237968a9967902691c0');

const a = await api.at('0x3361f6446c72aaa6679aa40a03e493a851161fd08cb53237968a9967902691c0');

console.log(Object.keys(a.query.balances));
console.log((await a.query.balances.freeBalance('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')).toHuman())
```

**Comment by TarikGul** [comment]
Thanks for the response on this! Will close due to this giving enough context to find a work around for our problem!

Thanks again.
