### ISSUE TITLE
Error: createType(u32):: Invalid character

### ISSUE THREAD

**Issue by forgetso** [polkadot-js/api#3904]
I'm getting an `Invalid character` message when I try to hash some text at 32 bytes and then pass it to my contract function.

```
// hashes to 0xf05a7ba662838be84b7512eb155ee72fbb8ef0e5367e41c663ca33488252a797
const serviceOrigin = blake2AsHex("https://localhost:2424", 256);

// call the contract function
await expect(contract.query.providerRegister(serviceOrigin, Bob, fee))
            .to.emit(contract, "register")
            .withArgs(Bob);
```

>        provider can register:
>      Error: createType(u32):: Invalid character
>       at createTypeUnsafe (node_modules/@polkadot/types/create/createType.cjs:68:18)
>       at MetaRegistry.createType (node_modules/@polkadot/types/create/registry.cjs:345:45)
>       at /home/user/dev/project/project-contract/node_modules/@polkadot/api-contract/Abi.cjs:151:36
>       at Array.map (<anonymous>)
>       at Abi.value (node_modules/@polkadot/api-contract/Abi.cjs:149:137)
>       at Object.toU8a (node_modules/@polkadot/api-contract/Abi.cjs:111:101)
>       at populateTransaction (node_modules/@redspot/patract/contract.js:25:27)
>       at Object.providerRegister (node_modules/@redspot/patract/contract.js:82:49)
>       at /home/user/dev/project/project-contract/tests/project.test.ts:42:37
>       at step (tests/project.test.ts:33:23)

If I change the call to use 128 bit  length instead, the underlying code correctly identifies the hash as 16 bytes so it seems to be something to do with 256 bit length.

```const serviceOrigin = blake2AsHex("https://localhost:2424", 128);```

Error message:

> Error: createType(Hash):: Expected at least 32 bytes (256 bits), found 16 bytes

I have polkadot types v5.6.1 installed and it outputs as 5.6.1 when I call ```console.log(packageInfo.version);```.

The contract is deployed using [redspot](https://github.com/patractlabs/redspot)

> ✗ node --version
> v14.17.3
> 
> ✗ yarn --version
> 1.22.11

**Comment by jacogr** [comment]
U32 does not take hashes, it takes numbers (or hex numbers)
