### ISSUE TITLE
RPC-CORE error when querying specific blocks on parachains (Karura, Moonbeam)

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#3915]
This error seems to be focused around parachains. I am not perfectly sure where the error is originating from, so any direction on whether this is a Karura / Moonbeam issue vs polkadot-js would be appreciated.

## Info

`@polkadot/api` v5.7.1
`@acala-network/type-definitions` v2.1.1 (Same as `@polkadot/apps-config`)
`moonbeam-types-bundle` v1.2.4 (Same as `@polkadot/apps-config`)

### Karura Block info
BlockHash: 0xcb7f7866a14f88bb19fd2b2c04303c381bd569c32413b7eac719e5ef8a40ba9c
BlockHeight: 438151

### Moonbeam Block info
BlockHash: 0x9caa779d514cac6d60e51797f88f05a2d5cb839bb6695f039e0810cf21c7b046
BlockHeight: 427542

The error below happens when querying a specific block on both Karura and Moonbeam. 

## Error

```
2021-08-30 12:12:21        RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: -32603: Unknown error occurred: Client, Application, NotInFinalizedChain
2021-08-30 12:12:21        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: -32603: Unknown error occurred: Client, Application, NotInFinalizedChain
Error: -32603: Unknown error occurred: Client, Application, NotInFinalizedChain
    at RpcCoder._checkError (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at WsProvider.value (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/@polkadot/rpc-provider/ws/index.cjs:239:90)
    at W3CWebSocket.value [as onmessage] (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/@polkadot/rpc-provider/ws/index.cjs:219:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame (/Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/tarik/Desktop/parity/sanity-checks/txwrapper-check/node_modules/websocket/lib/WebSocketConnection.js:323:40

```

### Karura

```javascript
import { ApiPromise, WsProvider } from '@polkadot/api';
import { typesBundle } from '@acala-network/type-definitions';


const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://karura-rpc-1.aca-api.network'),
        typesBundle
    });

    // Block 438151
    const result = await api.rpc.chain.getBlock('0xcb7f7866a14f88bb19fd2b2c04303c381bd569c32413b7eac719e5ef8a40ba9c')

    console.log(result.toHuman())
};
```

### Moonbeam

```javascript
import { ApiPromise, WsProvider } from '@polkadot/api';
import { typesBundle } from 'moonbeam-types-bundle'

const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://wss.moonriver.moonbeam.network'),
        typesBundle
    });

    // Block 427542
    const result = await api.rpc.chain.getBlock('0x9caa779d514cac6d60e51797f88f05a2d5cb839bb6695f039e0810cf21c7b046')

    console.log(result.toHuman())
};
```

**Comment by jacogr** [comment]
The Karura and Moonbeam types are managed by their teams. Please refer to them - if incorrect, it will yield issues.

**Comment by crystalin** [comment]
@jacogr I tried to look at it, but I don't see what type is missing ? 
We haven't changed our code/types recently so I'm not sure where that would come from

**Comment by crystalin** [comment]
Also I tried opening it with PolkadotJS App and it works fine:
https://polkadot.js.org/apps/#/explorer/query/427542

**Comment by xlc** [comment]
This is Substrate issue not relating to types. We also had similarly report https://github.com/AcalaNetwork/acala.js/issues/189
I cannot reproduce this with all of our public endpoints but we did receive multiple error reports...

**Comment by crystalin** [comment]
This is triggered by this issue: https://github.com/paritytech/substrate/issues/9660
A node can return the invalid blockHash for a given height
