### ISSUE TITLE
Create type fails with Uint8Array but succeeds with Hex value

### ISSUE THREAD

**Issue by mustermeiszer** [polkadot-js/api#3917]
Hi, 

I am not sure if this is an issue or expected behavior. I want to create a `StorageKey` type via `api.createType("StorageKey", input)`.

Depending on the input this function fails. Both inputs represent the same data but in different formats.
 * First variant: `input: Uint8Array` of length 47.
 * Second variant: `input: string`a hexadecimal representation of the array above.

With the first variant I get an error of:
```shell
Error: createType(StorageKey):: Bytes length 442112206 exceeds 10485760
    at createTypeUnsafe (/Users/frederik/Projects/playground/node_modules/@polkadot/types/create/createType.cjs:59:18)
    at createType (/Users/frederik/Projects/playground/node_modules/@polkadot/types/create/createType.cjs:81:10)
    at TypeRegistry.createType (/Users/frederik/Projects/playground/node_modules/@polkadot/types/create/registry.cjs:307:39)
    at ApiPromise.createType (/Users/frederik/Projects/playground/node_modules/@polkadot/api/base/Decorate.cjs:170:82)
    at /Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:85:38
    at step (/Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:33:23)
    at Object.next (/Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:14:53)
    at /Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:4:12)
```

If this is expected behavior I am fine, but wanted to check if this is an issue, as using the array is easier for me.

**Comment by mustermeiszer** [comment]
Appendix: 

Another error occurs when I create a `StorageKey` via the same api from an accounted. 

Again, depending on the variant it fails with `Uint8Array` and succeeds with hex-representation of the same array.

Error is: 
```shell
Error: createType(StorageKey):: Bytes: required length less than remainder, expected at least 54, found 32
    at createTypeUnsafe (/Users/frederik/Projects/playground/node_modules/@polkadot/types/create/createType.cjs:59:18)
    at createType (/Users/frederik/Projects/playground/node_modules/@polkadot/types/create/createType.cjs:81:10)
    at TypeRegistry.createType (/Users/frederik/Projects/playground/node_modules/@polkadot/types/create/registry.cjs:307:39)
    at ApiPromise.createType (/Users/frederik/Projects/playground/node_modules/@polkadot/api/base/Decorate.cjs:170:82)
    at /Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:93:38
    at step (/Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:33:23)
    at Object.next (/Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:14:53)
    at fulfilled (/Users/frederik/Projects/playground/build/202108_crowdloan/hack.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jacogr** [comment]
StorageKey is length-prefixed. If you pass a U8a it needs to be properly encoded with the compact u32 length prefix preiendes to the data.

**Comment by mustermeiszer** [comment]
Ah okay. How would I do this? Create an `api.crateType("Compact<u32>", Input.length())` and pre-pend to the array?

**Comment by jacogr** [comment]
When going from codec values, use toHex. From Uint8Array there is compactAddLenght in polkadot/util

**Comment by mustermeiszer** [comment]
Thanks again @jacogr!
