### ISSUE TITLE
i cann't connect to phala test network

### ISSUE THREAD

**Issue by maybeTomorrow** [polkadot-js/api#3922]
const wsProvider = new WsProvider('wss://para1-api.phala.network/ws/');

// const api = await ApiPromise.create({ provider: wsProvider });
ApiPromise.create({ provider: wsProvider })
2021-09-02 09:58:35        REGISTRY: Unknown signed extensions CheckMqSequence found, treating them as no-effect
2021-09-02 09:58:35        REGISTRY: Unable to resolve type BridgeChainId, it will fail on construction
2021-09-02 09:58:35        API/INIT: Error: FATAL: Unable to initialize the API: createType(BridgeChainId):: DoNotConstruct: Cannot construct unknown type BridgeChainId
    at EventEmitter.value (file:///F:/pro/poltest/node_modules/@polkadot/api/base/Init.js:66:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/FAQ#i-am-getting-a-unknown-types-found-no-types-for--error

The Phala team publishes their type definitions, https://github.com/Phala-Network/typedefs

**Comment by jacogr** [comment]
Closing, reference to external repo provided.
