### ISSUE TITLE
use MultiLocation X2 in xTokens.transfer report "Cannot map Enum JSON, unable to find 'parent' in parachain"

### ISSUE THREAD

**Issue by baidang201** [polkadot-js/api#3982]
i use     "@polkadot/api": "^5.7.1",

code is
```
api.tx.xTokens.transfer( 
        {"token":"DOT"},
        new BN(para_chain_to_relaychain_amount),
        {"parents":0 ,"interior": {X2:[{"parent":null},{AccountId32:{network: "Any",id: CHARLIE}}]}},
        300000000000000,
      );
```

error is 
```
Error: createType(Call):: Call: failed decoding xTokens.transfer:: Struct: failed on args: {"currency_id":"CurrencyId","amount":"Balance","dest":"MultiLocation","dest_weight":"Weight"}:: Struct: failed on dest: {"parents":"u8","interior":"JunctionsV1"}:: Struct: failed on interior: {"_enum":{"Here":"Null","X1":"JunctionV1","X2":"(JunctionV1,JunctionV1)","X3":"(JunctionV1,JunctionV1,JunctionV1)","X4":"(JunctionV1,JunctionV1,JunctionV1,JunctionV1)","X5":"(JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1)","X6":"(JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1)","X7":"(JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1)","X8":"(JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1,JunctionV1)"}}:: Enum(X2):: Tuple: failed on 0:: Cannot map Enum JSON, unable to find 'parent' in parachain, accountid32, accountindex64, accountkey20, palletinstance, generalindex, generalkey, onlychild, plurality
    at createTypeUnsafe (/root/transfertest/node_modules/@polkadot/types/create/createType.cjs:68:18)
    at TypeRegistry.createType (/root/transfertest/node_modules/@polkadot/types/create/registry.cjs:345:45)
    at extrinsicFn (/root/transfertest/node_modules/@polkadot/types/metadata/decorate/extrinsics/createUnchecked.cjs:24:21)
    at Object.decorated [as transfer] (/root/transfertest/node_modules/@polkadot/api/base/Decorate.cjs:390:46)
    at /root/transfertest/src/index.ts:209:30
    at step (/root/transfertest/src/index.ts:33:23)
    at Object.next (/root/transfertest/src/index.ts:14:53)
    at fulfilled (/root/transfertest/src/index.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Done in 4.66s.
```

can you show a good call exmple

**Comment by jacogr** [comment]
There is no parent in JunctionV1 - https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/xcm/v1.ts#L21

**Comment by baidang201** [comment]
thx,had fix.
just add in types.json
```
      AssetInstance: 'AssetInstanceV0',
      MultiAsset: 'MultiAssetV0',
      MultiLocation: 'MultiLocationV0',
      Response: 'ResponseV0',
      Xcm: 'XcmV0',
```


https://github.com/polkadot-js/api/issues/3941

```
It defaults to 1, most probably will be adjusted to 2.

For older XCM versions you will need to apply the correct overrides for your specific chain, eg. Kusama does the following, https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L196-L201
```
