### ISSUE TITLE
Cannot convert 'HistoricMetaCompat' via asTuple when use .at() 

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#3999]
Hi, I believe there are some issues when query `staking.erasStakers` with `.at()` with some early blocks. 

```
Network: Kusama

const blockHash_6721189 = `0x70070f6c1ad5b9ce3d0a09e94086e22b8d4f08a18491183de96614706bf59600`;
const blockHash_9428060 = `0xe3b3abc967b13e219e110a8b77fa77e6354c37ea310b9ce9fbca756d5b9a06bd`;

// Good with recent block
const recentEraStakers = await api.query.staking.erasStakers.at(
    blockHash_9428060,
    2795,
    `HnnFkvtzrSrNpSUdG47E9ioBmDoDBnRUL6Lmy7GeqGcFc5c`
);
//{total: 21777783287643145, own: 703977782503060, others: [{who: DzUzfG8j2bhFUBDHsmup5Lnuufwt1dyuxdYZbZy2fxR2d7f, value: 83335953}, {who: GtRQd4YsEJiHWyWws5yBCMLhWPTUELHVQEDFRCvfPMfnWKW, value: 14643496830328310}, {who: GRTHCT1fNRgbqMURtEDuZPBbQ7tHcgt3swzdmGNk1MKchqL, value: 6430308591475822}]}


// No problem here,  also can query reward points
const erasRewardPoints = await api.query.staking.erasRewardPoints.at(
    blockHash_6721189,
    2038,
);
//{total: 48840, individual: {CaKh7HmPMXxv22GnLgjEZxWHBUu7y7Twf2k8mP3mxpLYTH4: 40, CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc: 100, CaSTASQf6FjnBqGntCadoT1YbcNvBTMr5pbHwez6PZMJZW2: 40, CaVLqgMmajk7ySYjo4SPqauXwsZu8Y5tP9vVDvJvcecbp3n: 40, .....

//Not work, throw error
const erasStakers = await api.query.staking.erasStakers.at(
    blockHash_6721189,
    2038,
    'CaKh7HmPMXxv22GnLgjEZxWHBUu7y7Twf2k8mP3mxpLYTH4'
);
/***
Error: Cannot convert 'HistoricMetaCompat' via asTuple
    at a (https://polkadot.js.org/apps/polkadot.02.a784cc90.js:1:225017)
    at r.get [as asTuple] (https://polkadot.js.org/apps/polkadot.01.09b53147.js:1:164856)
    at Ta (https://polkadot.js.org/apps/polkadot.01.09b53147.js:1:95345)
    at n (https://polkadot.js.org/apps/polkadot.01.09b53147.js:1:111898)
    at Object.erasStakers (https://polkadot.js.org/apps/polkadot.01.09b53147.js:1:111971)
    at https://polkadot.js.org/apps/polkadot.01.09b53147.js:1:110736
    at https://polkadot.js.org/apps/other.01.a6e016b1.js:2:346735
    at t.i._next (https://polkadot.js.org/apps/other.01.a6e016b1.js:2:340172)
    at t.next (https://polkadot.js.org/apps/other.01.a6e016b1.js:2:329472)
    at https://polkadot.js.org/apps/other.01.a6e016b1.js:2:337974
***/
```

**Comment by jacogr** [comment]
Ummm… interesting. Thanks for the full details, will take a look.
