### ISSUE TITLE
api.queryMulti() issues

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#4006]
Hi thanks for fix previous .at() issue, but now when I have encounter some new issues when use `api.queryMulti()`

I tested following code with latest version `6.1.3-0` on Kusama:

```
const account = 'E7ncQKp4xayUoUdpraxBjT7NzLoayLJA4TuPcKKboBkJ5GH';
const result = await api.queryMulti([
      // case 1: without array
      api.query.timestamp.now,
      // case 2 : zero arg
      [api.query.session.validators],
      //case 3: one arg
      [api.query.system.account, account], 
      //case 4: //double map
      [
        api.query.staking.erasStakers,
        2038,
        `HAGcVQikZmEEgBBaChwjTVdwdA53Qopg2AYUtqw738C5kUq`,
      ], 
    ])
console.log(result);
```

- Case 1: Passed
- Case 2: Throw error :
```
Error: Cannot convert 'Plain' via asMap
    at assert (/Users/jiatwork/polkadot/api/node_modules/@polkadot/util/assert.js:24:11)
    at Type.asMap (/Users/jiatwork/polkadot/api/packages/types/src/codec/Enum.ts:213:17)
    at map (/Users/jiatwork/polkadot/api/packages/api/src/base/Decorate.ts:378:41)
    at Array.map (<anonymous>)
    at method (/Users/jiatwork/polkadot/api/packages/api/src/base/Decorate.ts:376:15)
    at /Users/jiatwork/polkadot/api/packages/api/src/promise/index.ts:68:40
    at new Promise (<anonymous>)
    at decorateCall (/Users/jiatwork/polkadot/api/packages/api/src/promise/index.ts:63:10)
    at ApiPromise.queryMulti [as _queryMulti] (/Users/jiatwork/polkadot/api/packages/api/src/promise/index.ts:105:9)
    at Object.<anonymous> (/Users/jiatwork/polkadot/api/packages/api/test/api.spec.ts:174:30)
```
- Case 3: Passed
- Case 4: Throw error: 
```
Error: createType(Vec<StorageKey>):: Found non-callable @@iterator
    at createTypeUnsafe (/Users/jiatwork/polkadot/api/packages/types/src/create/createType.ts:73:18)
    at TypeRegistry.createTypeUnsafe (/Users/jiatwork/polkadot/api/packages/types/src/create/registry.ts:261:12)
    at map (/Users/jiatwork/polkadot/api/packages/rpc-core/src/bundle.ts:342:16)
    at Array.map (<anonymous>)
    at RpcCore._formatInputs (/Users/jiatwork/polkadot/api/packages/rpc-core/src/bundle.ts:341:19)
    at Observable._subscribe (/Users/jiatwork/polkadot/api/packages/rpc-core/src/bundle.ts:285:31)
    at Observable.Object.<anonymous>.Observable._trySubscribe (/Users/jiatwork/polkadot/api/node_modules/rxjs/src/internal/Observable.ts:244:19)
    at /Users/jiatwork/polkadot/api/node_modules/rxjs/src/internal/Observable.ts:234:18
    at Object.errorContext (/Users/jiatwork/polkadot/api/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Observable.Object.<anonymous>.Observable.subscribe (/Users/jiatwork/polkadot/api/node_modules/rxjs/src/internal/Observable.ts:220:5)
```

**Comment by jacogr** [comment]
Not 100% convinced the format is correct (and I may be speaking bull here)... I believe it should be -

[
        api.query.staking.erasStakers,
        [2038, `HAGcVQikZmEEgBBaChwjTVdwdA53Qopg2AYUtqw738C5kUq`],
],

i.e. array params for the map form.

Having said that, the above error should not be there.

**Comment by jiqiang90** [comment]
Hi @jacogr, thanks for the quick response, I updated to 6.1.3-1, but for the 2nd case `[api.query.session.validators]`  error still remains.
