### ISSUE TITLE
Further question regard api.queryMulti() format 

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#4010]
Hi , still regarding previous issue(https://github.com/polkadot-js/api/issues/4006). I need your help to clarify whether api.queryMulti still support this format I found inside the manual.
https://github.com/polkadot-js/api/blob/651afaeb9a1e967545a06a7c6e444cb36b1938d0/packages/api/src/checkTypes.manual.ts#L92

For the 2nd case in my previous issue, I did some tests: 

```
// method not wrapped in []
await api.queryMulti([api.query.session.validators]). // This works for either 5.9.1 or 6.1.3-1.
```
However, this format

```
//method wrapped in []
await api.queryMulti([[api.query.session.validators]])
```
It works in 5.9.1, but **NOT** work in 6.1.3-1 and throw following error.
```
Error: Cannot convert 'Plain' via asMap
    at assert (/Users/jiatwork/polkadot/api/node_modules/@polkadot/util/assert.js:24:11)
    at Type.asMap (/Users/jiatwork/polkadot/api/packages/types/src/codec/Enum.ts:213:17)
    at map (/Users/jiatwork/polkadot/api/packages/api/src/base/Decorate.ts:378:41)
    at Array.map (<anonymous>)
    at method (/Users/jiatwork/polkadot/api/packages/api/src/base/Decorate.ts:376:15)
    at /Users/jiatwork/polkadot/api/packages/api/src/promise/index.ts:84:40
    at new Promise (<anonymous>)
    at decorateSubscribe (/Users/jiatwork/polkadot/api/packages/api/src/promise/index.ts:79:10)
    at ApiPromise.queryMulti [as _queryMulti] (/Users/jiatwork/polkadot/api/packages/api/src/promise/index.ts:104:9)
    at Object.<anonymous> (/Users/jiatwork/polkadot/api/packages/api/test/api.spec.ts:199:34)
```

Is this a bug or we no longer support this format, so call method without any args should always not wrapped in the [] ? Thank you.

**Comment by jacogr** [comment]
Generally there is no need to wrap a method without args. However, the above should really work, as it did previously.
