### ISSUE TITLE
createType(Lookup36) error when uses expandMetadata with westend.

### ISSUE THREAD

**Issue by TarikGul** [polkadot-js/api#4015]
rel: [#690](https://github.com/paritytech/substrate-api-sidecar/issues/690)

## @polkadot/api version: 

This error starts at 6.0.1 and is reproducible up until 6.1.3. 

## The Error:

```
createType(Lookup36):: Unable to create Enum via index 112, in InvalidEquivocationProof, InvalidKeyOwnershipProof, DuplicateOffenceReport
    at createTypeUnsafe (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/types/create/createType.cjs:68:18)
    at TypeRegistry.createTypeUnsafe (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/types/create/registry.cjs:364:45)
    at /Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/types/metadata/decorate/constants/index.cjs:28:30
    at Array.reduce (<anonymous>)
    at /Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/types/metadata/decorate/constants/index.cjs:27:58
    at Array.reduce (<anonymous>)
    at decorateConstants (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/types/metadata/decorate/constants/index.cjs:18:18)
    at expandMetadata (/Users/tarik/Desktop/parity/sanity-checks/polka-test/node_modules/@polkadot/types/metadata/decorate/index.cjs:63:42)
    at main (/Users/tarik/Desktop/parity/sanity-checks/polka-test/index.js:13:22)
```

Two blocks where this is happening are:
5495855,
5493461

## Steps to reproduce:

```
const main = async () => {
    const api = await ApiPromise.create({
        provider: new WsProvider('wss://westend-rpc.polkadot.io'),
    });

    const hash = await api.rpc.chain.getBlockHash(5493461)
    const metadata = await api.rpc.state.getMetadata(hash);

    const decorate = expandMetadata(api.registry, metadata);

    console.log(decorate);
};
```

**Comment by jacogr** [comment]
You cannot use api.registry for expand in older blocks. This is why you have the issue. A registry instance is per specVersion, not shared across all since it contains unique types across each upgrade.

**Comment by TarikGul** [comment]
Ahh yes, thanks for pointing that out. `Api.at` should do the trick. Sorry for the simple mistake, I really overthought it this time.
