### ISSUE TITLE
got error message "PolkadotPrimitivesV1SignedUncheckedSigned"

### ISSUE THREAD

**Issue by code-brewer** [polkadot-js/api#4060]
I have a backend application that scan Polkdot tx. It run well in pass two months until 2 days ago.

It first throws error:  "Unable to create Enum via index 104, in Optional, Default, Required" 
 
**SOLUTION: I solve it by upgrade "@polkadot/api" to the latest version. ( from ver "5.2.1" to "6.3.1" )**

However, today, I got another error message: **"DoNotConstruct: Cannot construct unknown type 
PolkadotPrimitivesV1SignedUncheckedSigned".** 

It is very hard to figure out what's wrong. 

```
storeman0x5c770cbf582d770b93ca90adad7e6bd33fabc44c 2021-10-14 11:10:47,804 storemanAgent-sync INFO Polka getBlockNumberSync() catch error:  createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: {"data":"{\"bitfields\":\"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>\",\"backedCandidates\":\"Vec<PolkadotPrimitivesV1BackedCandidate>\",\"disputes\":\"Vec<PolkadotPrimitivesV1DisputeStatementSet>\",\"parentHeader\":\"{\\\"parentHash\\\":\\\"H256\\\",\\\"number\\\":\\\"Compact<u32>\\\",\\\"stateRoot\\\":\\\"H256\\\",\\\"extrinsicsRoot\\\":\\\"H256\\\",\\\"digest\\\":\\\"{\\\\\\\"logs\\\\\\\":\\\\\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\\\\\"}\\\"}\"}"}:: decodeU8a: failed at 0x4014020000000036▒~@▒ on data: {"bitfields":"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>","backedCandidates":"Vec<PolkadotPrimitivesV1BackedCandidate>","disputes":"Vec<PolkadotPrimitivesV1DisputeStatementSet>","parentHeader":"{\"parentHash\":\"H256\",\"number\":\"Compact<u32>\",\"stateRoot\":\"H256\",\"extrinsicsRoot\":\"H256\",\"digest\":\"{\\\"logs\\\":\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\"}\"}"}:: decodeU8a: failed at 0x4014020000000036▒~@▒ on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0x140200000000364e▒~@▒ on :: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding paraInherent.enter:: Struct: failed on args: {"data":"{\"bitfields\":\"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>\",\"backedCandidates\":\"Vec<PolkadotPrimitivesV1BackedCandidate>\",\"disputes\":\"Vec<PolkadotPrimitivesV1DisputeStatementSet>\",\"parentHeader\":\"{\\\"parentHash\\\":\\\"H256\\\",\\\"number\\\":\\\"Compact<u32>\\\",\\\"stateRoot\\\":\\\"H256\\\",\\\"extrinsicsRoot\\\":\\\"H256\\\",\\\"digest\\\":\\\"{\\\\\\\"logs\\\\\\\":\\\\\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\\\\\"}\\\"}\"}"}:: decodeU8a: failed at 0x4014020000000036▒~@▒ on data: {"bitfields":"Vec<PolkadotPrimitivesV1SignedUncheckedSigned>","backedCandidates":"Vec<PolkadotPrimitivesV1BackedCandidate>","disputes":"Vec<PolkadotPrimitivesV1DisputeStatementSet>","parentHeader":"{\"parentHash\":\"H256\",\"number\":\"Compact<u32>\",\"stateRoot\":\"H256\",\"extrinsicsRoot\":\"H256\",\"digest\":\"{\\\"logs\\\":\\\"Vec<SpRuntimeGenericDigestDigestItem>\\\"}\"}"}:: decodeU8a: failed at 0x4014020000000036▒~@▒ on bitfields: Vec<PolkadotPrimitivesV1SignedUncheckedSigned>:: decodeU8a: failed at 0x140200000000364e▒~@▒ on :: DoNotConstruct: Cannot construct unknown type PolkadotPrimitivesV1SignedUncheckedSigned
    at createTypeUnsafe (/snapshot/js-storeman-agent/node_modules/@polkadot/types/create/createType.cjs:68:18)
    at TypeRegistry.createTypeUnsafe (/snapshot/js-storeman-agent/node_modules/@polkadot/types/create/registry.cjs:364:45)
    at RpcCore._formatOutput (/snapshot/js-storeman-agent/node_modules/@polkadot/rpc-core/bundle.cjs:389:21)
    at callWithRegistry (/snapshot/js-storeman-agent/node_modules/@polkadot/rpc-core/bundle.cjs:255:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Can anyone give some hints, suggestions?  Thanks

**Comment by jacogr** [comment]
Closing, Please log if the issue is in a recent API version.
