### ISSUE TITLE
Failing to decode using metadata types

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#4187]
(Sorry if this was already posted I'm having a hard time to keep track of all the types issues :( )

When trying to access a block on a Moonbeam node using runtime 900 (using scale-info)., I get this.

Error:
```
2021-11-09 03:34:55             VEC: Unable to decode on index 3 createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: decodeU8a: failed at 0xacf599709bf070449e0ccebbef96e60b… on signer: {"_enum":{"Id":"AccountId","Index":"Compact<AccountIndex>","Raw":"Bytes","Address32":"H256","Address20":"H160"}}:: Unable to create Enum via index 172, in Id, Index, Raw, Address32, Address20
2021-11-09 03:34:55        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: decodeU8a: failed at 0xacf599709bf070449e0ccebbef96e60b… on signer: {"_enum":{"Id":"AccountId","Index":"Compact<AccountIndex>","Raw":"Bytes","Address32":"H256","Address20":"H160"}}:: Unable to create Enum via index 172, in Id, Index, Raw, Address32, Address20
(node:44751) UnhandledPromiseRejectionWarning: Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: decodeU8a: failed at 0xacf599709bf070449e0ccebbef96e60b… on signer: {"_enum":{"Id":"AccountId","Index":"Compact<AccountIndex>","Raw":"Bytes","Address32":"H256","Address20":"H160"}}:: Unable to create Enum via index 172, in Id, Index, Raw, Address32, Address20
    at createTypeUnsafe (/home/alan/projects/moonbeam-tools/node_modules/@polkadot/types/create/createType.cjs:75:18)
    at TypeRegistry.createTypeUnsafe (/home/alan/projects/moonbeam-tools/node_modules/@polkadot/types/create/registry.cjs:419:45)
    at RpcCore._formatOutput (/home/alan/projects/moonbeam-tools/node_modules/@polkadot/rpc-core/bundle.cjs:412:21)
    at RpcCore._formatResult (/home/alan/projects/moonbeam-tools/node_modules/@polkadot/rpc-core/bundle.cjs:237:27)
    at callWithRegistry (/home/alan/projects/moonbeam-tools/node_modules/@polkadot/rpc-core/bundle.cjs:261:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Code:
```
import { ApiPromise, WsProvider } from "@polkadot/api";

const main = async () => {
  const api = await ApiPromise.create({
    provider: new WsProvider(`wss://wss.testnet.moonbeam.network`),
  });

  console.log((await api.rpc.chain.getBlock()).toHuman());
  await api.disconnect();
};

main();
```
(block hash if needed: 0x333a38ab14cd1747eb82a800e487068670a34ff0cdc2b54ec334e32e2b796584)

**Comment by jacogr** [comment]
RPCs are problematic. While it has been designed with types in mind (see the rpc_methods versioning), it does not actually specify types in the metadata. 

So for these, you will need to I levy at least the AccoutId types.

**Comment by jacogr** [comment]
Confirmed, it is the Address/AccountId types. This is a gap where we need to try an extract more info for use.

**Comment by jacogr** [comment]
Try 6.7.2 (I tested it without types in the apps UI on both the chain, random blocks with transcations as well as the mentioned blockHash)

Basically what is does it detect the AccountId, Address & ExtrinsicSignature types from the sp_runtime::generic::UncheckedExtrinsic type.
