### ISSUE TITLE
Unable to use Jest with Polkadot, seems one of the dependent packages is missing a module type

### ISSUE THREAD

**Issue by codemaster101** [polkadot-js/api#4233]
```
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/<redacted>/polkadot/node_modules/@polkadot/keyring/index.js:3
    import "./detectPackage.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { encodeAddress } from '@polkadot/keyring';
        | ^
      2 | import { hexToU8a, isHex } from '@polkadot/util';
      3 | import { decodeAddress } from '@polkadot/util-crypto';
      4 | import { IValidAddress } from './interfaces';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/wallet-common.ts:1:1)
```

Pretty easy to recreate:
Import `encodeAddress` with `tsConfig.json` test case with:
```
{
  "compilerOptions": {
    "strict": true,
    "types": [
      "node",
      "jest"
    ],
    "target": "ES2020",
    "declaration": true,
    "rootDir": "./src/",
    "outDir": "./built/",
    "module": "commonjs",
    "skipLibCheck": true,
    "noImplicitAny": true,
    "removeComments": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "preserveConstEnums": true,
    "allowSyntheticDefaultImports": true,
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules/**/*"]
}
```

jest config test case with:
```
module.exports = {
  preset: 'ts-jest',
  testTimeout: 10000,
  testEnvironment: 'node',
  testMatch: ["**/?(*.(test|spec).ts)"],
  transformIgnorePatterns: ["/node_modules/@polkadot/*"],
  moduleFileExtensions: ["js", "ts", "json", "node"],
};
```

Versions that we are running:
Testing:
```
    "jest": "^27.3.1",
    "ts-jest": "^27.0.7",
    "ts-node": "^10.2.1",
    "typescript": "^4.4.3"
```

Polkadot specific:
```
    "@polkadot/api": "^6.7.1",
    "@polkadot/dev": "^0.63.28",
    "@polkadot/keyring": "^7.8.2",
    "@polkadot/types": "^6.7.2",
    "@polkadot/util": "^7.8.2",
    "@polkadot/util-crypto": "^7.8.2",
```

Although we've tried all sorts of combinations and permutations to make it work, we strongly believe it's because of the polkadot missing some sort of detail since we do not run into the issue without polkadot.

Let us know if we need to upgrade to a different version or try something else?

**Comment by jacogr** [comment]
All the repos here use Jest. It is because it doesn't handle exports maps correctly. So the transformIgnore patterns are one tweak, for the rest refer to the Jest docs for ESM.

 However since you are using ts-jest, the transformIgnore may not be needed or maybe should be explicitly included rather, sadly I'm not an expert on that tool, or Jest so cannot quite help "tweak" it.

**Comment by lcovar** [comment]
We are also running into this same error when using jest and importing @polkadot/api dependency. Any suggestions or workarounds?

**Comment by TarikGul** [comment]
@lcovar @codemaster101 Feel free to take a look at our configs for babel, and jest that solved this for us a while back. 
https://github.com/paritytech/substrate-js-dev/tree/main/config

**Comment by jacogr** [comment]
Closing. There has a been a number of issues around this one, with the same solution as in the comment just before mine. 

For Jest-specific support, if there is anything else, would refer to the Jest repos, they are the guys working on ESM support.
