### ISSUE TITLE
6.5.1 TypeError: (0 , _typesKnown.mapXcmTypes) is not a function

### ISSUE THREAD

**Issue by Deekor** [polkadot-js/api#4251]
Recently upgraded to version 6.5.1 and am now getting this error on TS compile:

```
TypeError: (0 , _typesKnown.mapXcmTypes) is not a function
    at Object.<anonymous> (/Users/dee/Repos/angular/pexp-server/node_modules/@polkadot/types/interfaces/xcm/definitions.cjs:90:183)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/dee/Repos/angular/pexp-server/node_modules/@polkadot/types/interfaces/definitions.cjs:441:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**Comment by jacogr** [comment]
Ensure the versions all match, i.e. types-known has the mapXcm - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/xcm.ts#L8 exported here https://github.com/polkadot-js/api/blob/master/packages/types-known/src/bundle.ts#L19

(In previous versions it was not there)

**Comment by Deekor** [comment]
My package.josn has both `"@polkadot/api": "6.5.1"` and `"@polkadot/types": "6.5.1"`

**Comment by Deekor** [comment]
Oh. I see i need to install `"@polkadot/types-known": "6.5.1"`.

I've never needed the `types-known` package before. What does it do?

**Comment by jacogr** [comment]
types-known should be a dependency of `@polkadot/types` - it doesn't seem like it is, so should be added, https://github.com/polkadot-js/api/blob/master/packages/types/package.json#L25-L29 (which means it should be upgraded alongside)
