### ISSUE TITLE
Jest test spyon getMetadata.raw method get Error: processTicksAndRejections

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#4529]
Hi @jacogr , I'm doing a test for our project. One of the test failed very strangely, which I want to spy on the `_rpcCore.state.getMetadata.raw` and  got following errors. 

```
Error: 
    at _super (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new UnsubscriptionErrorImpl (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/util/UnsubscriptionError.ts:22:7)
    at SafeSubscriber.Object.<anonymous>.Subscription.unsubscribe (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscription.ts:97:15)
    at SafeSubscriber.Object.<anonymous>.Subscriber.unsubscribe (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:113:24)
    at Object.next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/firstValueFrom.ts:62:20)
    at Object.next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:194:14)
    at SafeSubscriber.Object.<anonymous>.Subscriber._next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at SafeSubscriber.Object.<anonymous>.Subscriber.next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at OperatorSubscriber.Object.<anonymous>.Subscriber._next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at OperatorSubscriber.Object.<anonymous>.Subscriber.next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subject.ts:63:20
    at Object.errorContext (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at ReplaySubject.Object.<anonymous>.Subject.next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subject.ts:58:5)
    at ReplaySubject.Object.<anonymous>.ReplaySubject.next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/ReplaySubject.ts:65:15)
    at OperatorSubscriber.Object.<anonymous>.Subscriber._next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at OperatorSubscriber.Object.<anonymous>.Subscriber.next (/Users/jiatwork/subql3/api-test/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /Users/jiatwork/subql3/api-test/node_modules/@polkadot/rpc-core/bundle.cjs:273:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)

```

Here is my test code: https://github.com/jiqiang90/api-jest-test, you can run it from `api.spec.ts`

I have tested, It is working fine on **v7.5.2-8** and earlier version, but afterward and recent **v7.6.1** will fail.

Really appreciate your help

**Comment by jacogr** [comment]
This is the PR that, upon merging, resulted in 7.5.2-9 - https://github.com/polkadot-js/api/pull/4505/files

It was a real memory leak issue, my guess it it worked earlier because it never cleaned up.

**Comment by jiqiang90** [comment]
Thanks, this ticket can be close now. I have found another way to spy on the `getMetadata`.
