### ISSUE TITLE
Unexpected error for api.rpc.chain.getBlock

### ISSUE THREAD

**Issue by mkchungs** [polkadot-js/api#4605]
Steps to Reproduce the Error (running in local node terminal):

```
const {
    ApiPromise,
    WsProvider
} = require('@polkadot/api');

wssEndpoint = "wss://wss.moonriver.moonbeam.network"
var api = await ApiPromise.create({
    provider: new WsProvider(wssEndpoint)
});
await api.isReady;
let blockhash = '0x5819e5558f9c88497bdb5c7b038df4704176f25db3fab838530e86b07df4c8c9'
var signedBlock = await api.rpc.chain.getBlock(blockhash) //block 429700 of https://moonriver.subscan.io/block/429700
```

Error Msg:

```
2022-02-25 12:55:21             VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding authorInherent.setAuthor:: Struct: failed on args: :: decodeU8a: failed at 0x18824cdd6baadde0db8997da795cb025… on author:: DoNotConstruct: Cannot construct unknown type AuthorId
2022-02-25 12:55:21        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding authorInherent.setAuthor:: Struct: failed on args: :: decodeU8a: failed at 0x18824cdd6baadde0db8997da795cb025… on author:: DoNotConstruct: Cannot construct unknown type AuthorId
Uncaught:
Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding authorInherent.setAuthor:: Struct: failed on args: :: decodeU8a: failed at 0x18824cdd6baadde0db8997da795cb025… on author:: DoNotConstruct: Cannot construct unknown type AuthorId
    at createTypeUnsafe (/root/go/src/github.com/wolkdb/paraholic/node_modules/@polkadot/api/node_modules/@polkadot/types-create/create/type.cjs:73:18)
    at TypeRegistry.createTypeUnsafe (/root/go/src/github.com/wolkdb/paraholic/node_modules/@polkadot/api/node_modules/@polkadot/types/create/registry.cjs:323:46)
    at RpcCore._formatOutput (/root/go/src/github.com/wolkdb/paraholic/node_modules/@polkadot/api/node_modules/@polkadot/rpc-core/bundle.cjs:413:21)
    at RpcCore._formatResult (/root/go/src/github.com/wolkdb/paraholic/node_modules/@polkadot/api/node_modules/@polkadot/rpc-core/bundle.cjs:222:27)
    at callWithRegistry (/root/go/src/github.com/wolkdb/paraholic/node_modules/@polkadot/api/node_modules/@polkadot/rpc-core/bundle.cjs:250:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

List of packages that we are using:
```
# npm list
paraholic@0.1.0 /root/go/src/github.com/wolkdb/paraholic
├── @google-cloud/bigtable@3.9.2
├── @polkadot/api@7.9.2-10
├── @polkadot/extension-dapp@0.42.7
├── @polkadot/keyring@8.4.1
├── @polkadot/util-crypto@8.4.1
├── @polkadot/util@8.4.1
├── @polkadot/wasm-crypto@4.5.1
```

However, the similar code is working fine when trying on polkadot.js App (which is currently using the same api v7.9.2-10)
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonriver.moonbeam.network#/js

```
var blockHash = '0x5819e5558f9c88497bdb5c7b038df4704176f25db3fab838530e86b07df4c8c9'
var signedBlock = await api.rpc.chain.getBlock(blockHash) //block 429700 
console.log(`signedBlock(decoded)`, JSON.stringify(signedBlock.toHuman()))
var sn = JSON.parse(JSON.stringify(signedBlock))
console.log(`signedBlock(raw)`, JSON.stringify(sn))

var apiAt = await api.at(blockHash)
console.log(`set apiAt at ${blockHash}`)

console.log(`ex2(decoded)`,JSON.stringify(signedBlock.block.extrinsics[2].toHuman()))
console.log(`ex2(raw)`,sn.block.extrinsics[2]) //0x8c04150018824cdd6baadde0db8997da795cb02520bbc39163f4184da4a186b82bc1420f

var ex2a = apiAt.registry.createType('ExtrinsicV4', sn.block.extrinsics[2]);
console.log(`ex2a(decoded)`,JSON.stringify(ex2a.toHuman()))

var signedBlock2 = apiAt.registry.createType('SignedBlock', sn);
console.log(`decoded SignedBlock`, JSON.stringify(signedBlock2.toHuman()))
```

How can we resolve the error?

**Comment by jacogr** [comment]
The apps UI injects the types that the Moonbeam team publishes, see  https://github.com/PureStake/moonbeam/tree/master/moonbeam-types-bundle

**Comment by mkchungs** [comment]
Thanks, that works!
