### ISSUE TITLE
Unable to decode type

### ISSUE THREAD

**Issue by sushi30** [polkadot-js/api#4625]
I am trying to run the an API call against a Shiden node. Hitting this error regarding decoding. The types match the definition in the pallet.

```javascript
  ~/dev/astar-js-demo on   master ❯ ts-node index.ts                                                                                                   at  14:06:32
2022-03-03 14:06:40        API/INIT: RPC methods not decorated: eth_feeHistory
{ version: '336' }
2022-03-03 14:06:41        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage dappsStaking.contractEraStake:: createType(PalletDappsStakingEraStakingPoints):: decodeU8a: failed at 0xd38515e62f83f804861803773ae17af0… on stakers: BTreeMap<AccountId,Balance>:: Number can only safely store up to 53 bits
/home/imri/dev/astar-js-demo/node_modules/@polkadot/rpc-core/bundle.cjs:477
      throw new Error(`Unable to decode storage ${key.section || 'unknown'}.${key.method || 'unknown'}:${entryNum}: ${error.message}`);
            ^
Error: Unable to decode storage dappsStaking.contractEraStake:: createType(PalletDappsStakingEraStakingPoints):: decodeU8a: failed at 0xd38515e62f83f804861803773ae17af0… on stakers: BTreeMap<AccountId,Balance>:: Number can only safely store up to 53 bits
    at RpcCore._newType (/home/imri/dev/astar-js-demo/node_modules/@polkadot/rpc-core/bundle.cjs:477:13)
    at RpcCore._formatStorageData (/home/imri/dev/astar-js-demo/node_modules/@polkadot/rpc-core/bundle.cjs:422:17)
    at RpcCore._formatOutput (/home/imri/dev/astar-js-demo/node_modules/@polkadot/rpc-core/bundle.cjs:396:19)
    at RpcCore._formatResult (/home/imri/dev/astar-js-demo/node_modules/@polkadot/rpc-core/bundle.cjs:237:27)
    at callWithRegistry (/home/imri/dev/astar-js-demo/node_modules/@polkadot/rpc-core/bundle.cjs:261:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The repo to reproduce can found [here](https://github.com/sushi30/astar-js-minimal-script).

**Comment by jacogr** [comment]
`"@polkadot/api": "^6.8.1"` Please update and recheck, cannot support nor debug non-current versions.
