### ISSUE TITLE
Read storage, at a specific blockhash: await api.at(blockHash);

### ISSUE THREAD

**Issue by Chralt98** [polkadot-js/api#4635]
The code says, that an access with "await api.at(blockHash);" is deprecated. How could I use it correctly in the new way? Or is there another method to run legacy code.

Example:

```javascript
// save the block hash for verification purpose
const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
// query the active era data in form of an optional data structure at a specific block
const activeEraOptional = await api.query.staking.activeEra.at(blockHash);
```

https://polkadot.js.org/docs/api/examples/promise/read-storage-at

TypeError: Cannot read properties of undefined (reading 'at')
    at main (/root/query_data.js:27:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)

**Comment by jacogr** [comment]
```js
const blockHash = await api.rpc.chain.getBlockHash(blockNumber);
const apiAt = await api.at(blockHash);

// at this point the apiAt object is decorated with the metadata as blockHash
const activeEraOptional = await apiAt.query.staking.activeEra();
```

**Comment by Chralt98** [comment]
Please mark this in the documentation too :-) thanks!

**Comment by jacogr** [comment]
PRs to documentation welcome in https://github.com/polkadot-js/docs - I sadly cannot get to everything atm, so help is always welcome.

**Comment by Chralt98** [comment]
What if I want to use the following:

const apiAtEra = await api.at(blockHash, era);

Does this work fine too?

Currently I get the following error message:

Error: Unable to retrieve header and parent from supplied hash
    at assert (/root/node_modules/@polkadot/util/assert.cjs:37:11)
    at ApiPromise._getBlockRegistry (/root/node_modules/@polkadot/api/base/Init.cjs:194:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
    But this could be, because I have not fully downloaded the kusama blockchain...

**Comment by Chralt98** [comment]
The full code is the following:

```javascript
// import the Polkadot API library for querying data from the node
const { ApiPromise } = require('@polkadot/api');
// import the file system library for writing the data to a CSV file
var fs = require('fs');

async function main() {
    // create an instance of the Polkadot API to use that constant later
    const api = await ApiPromise.create();

    // api.query of .balances.totalIssuance and .staking.erasTotalStake are only available starting at block 1491598 
    // the functionality wasn't implemented before
    let blockNumber = 1491598;

    // open a CSV file in append mode
    var stream = fs.createWriteStream("staking_rate.csv", { flags: 'a' });

    // write the first row of the CSV file for the column information
    stream.write("Date;EraIndex;StakedToken;TotalToken;BlockNumber;BlockHash\n");

    // initialize a variable to check if the Era has changed
    let lastEra = 0;
    // query constantly until the current block and get new incoming blocks too
    while (true) {
        // save the block hash for verification purpose
        const blockHash = await api.rpc.chain.getBlockHash(blockNumber);

        // query the active era data in form of an optional data structure at a specific block
        const apiAt = await api.at(blockHash);
        const activeEraOptional = await apiAt.query.staking.activeEra();

        // if there is a value in the option data structure then enter the code in the following curly brackets
        if (activeEraOptional.isSome) {
            // unpack the active era optional to get the index number
            const era = activeEraOptional.unwrap().index;

            // only once in each era the staked and total tokens change 
            if (era.toNumber() != lastEra) {
                // saving for checks if the active era changes in the future blocks
                lastEra = era;

                // save the unix timestamp for data visualizations
                const timestamp = await api.query.timestamp.now.hash(blockHash);
                // convert that unix timestamp to a human readable format
                const date = new Date(timestamp.toNumber()).toLocaleString();

                const apiAtEra = await api.at(blockHash, era);

                // query and save the amount of KSM in staking at a specific time
                const stakedToken = await apiAtEra.query.staking.erasTotalStake();
                // query and save the total amount of KSM at that specific time too
                const totalToken = await apiAt.query.balances.totalIssuance();

                // print the values to the console for debug purposes
                console.log('%s; %s era index; %s block number; %s staked token and %s total token for block hash %s',
                    date, era.toNumber(), blockNumber, stakedToken.toHuman(), totalToken.toHuman(), blockHash);

                // write that data to the CSV file
                stream.write(date.toString() +
                    ';' + era.toNumber().toString() +
                    ';' + stakedToken.toHuman().toString() +
                    ';' + totalToken.toHuman().toString() +
                    ';' + blockNumber.toString() +
                    ';' + blockHash.toString() + '\n');
            }
        }
        // increase the block number to jump ideally to the next era and finding out the staking rate (staked token )
        blockNumber++;
    }
}

// if the main function catches an error, then exit the node javascript process
main().catch(console.error).finally(() => process.exit());

```

**Comment by jacogr** [comment]
The api.at only takes the blockHash. The instance then is decorated as per any normal query. i.e. if the query takes an `era` param as per https://polkadot.js.org/docs/substrate/storage you need to pass it.

Basically the `apiAt` is just a normal api instance - on queries it just points to a specific blockHash & metadata.

Be aware that the decoration is "at that point in the chain", to give an example if you try and do the above at block 100 on Kusama, it will most probably fail. At that point the staking interfaces looked very different, so different methods are exposed on the `apiAt` instance under the `staking` module. (The same applies to all modules, each runtime update brings new modules and interface adjustments that is exposed in the on-chain metadata)

**Comment by Chralt98** [comment]
Thanks @jacogr !
