### ISSUE TITLE
Generate types from chain doesn't work

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/api#4752]
I'm unable to get a types file to generate from the following script: `yarn polkadot-types-from-chain --endpoint ws://localhost:9944 --output ./packages/types/src`. It generates everything but a type file. If I don't have any custom definitions and using only the Metdata from the chain, should I expect the build system to generate types for my custom chain?

I'm a bit confused how to properly generate types against a new chain give the docs are quite out-of-date.

**Comment by jacogr** [comment]
It still needs the custom definitions, even if fully empty. (They certainly still get used in e.g. RPCs, so the need has not been removed)

**Comment by drewstone** [comment]
So I use the following script:
```
yarn polkadot-types-from-defs --input packages/types/src/interfaces --package sample-polkadotjs-typegen/interfaces --endpoint packages/types/src/metadata/metadata.json
```
This leads to the following error:
```
$ /Users/drew/webb/webb.js/node_modules/.bin/polkadot-types-from-defs --input packages/types/src/interfaces --package sample-polkadotjs-typegen/interfaces --endpoint packages/types/src/metadata/metadata.json
/Users/drew/webb/webb.js/packages/types/src/interfaces/lookup.ts
	Generating
	Writing

/Users/drew/webb/webb.js/packages/types/src/interfaces/definitions.ts:4
export { default as merkle } from './merkle/definitions.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at main (/Users/drew/webb/webb.js/node_modules/@polkadot/typegen/cjs/fromDefs.js:58:20)
    at module.exports (/Users/drew/webb/webb.js/node_modules/@polkadot/typegen/scripts/execWithSrc.cjs:35:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Nonetheless, after this process, there is now:
- `lookup.ts`
- `registry.ts`
- `types-lookup.ts`
- `index.ts`
There is no `types.ts` file though and `index.ts` still searches for it.

I needed to add the following line to my `tsconfig.json` from another issue I found online:
```
"@polkadot/types/lookup": [
        "packages/types/src/interfaces/types-lookup.ts"
      ],
```

Does this sound correct still? What's odd with this too is that when the augmented files are created as per our script, they don't contain any imports of the types themselves even though they call them. Therefore, I have to manually go in to my editor and `add all missing imports` to add them all from the `types-lookup.ts`

If you're familiar with some ways to debug this the branch/package is the `types` one here: https://github.com/webb-tools/webb.js/tree/drew/updates/packages/types.
