### ISSUE TITLE
Generate lookup types error

### ISSUE THREAD

**Issue by cinlk** [polkadot-js/api#4799]
the  @polkadot/typegen v8.1.2-1 and a chain with metadata v14.

``` 
** Generating lookup for pangolin
2022-05-08 22:03:47        REGISTRY: Unknown signed extensions CheckEthereumRelayHeaderParcel found, treating them as no-effect
packages/types-augment/src/lookup/pangolin/lookup.ts
	Generating
	Writing

/Users/lk/jsProject/itering/darwinia.js/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:55
  throw new Error(`Generate: ${def.name || ''}: Unhandled type ${_typesCreate.TypeDefInfo[def.info]}`);
  ^

Error: Generate: Range: Unhandled type Range
    at Object.errorUnhandled (/Users/lk/jsProject/itering/darwinia.js/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:55:9)
    at /Users/lk/jsProject/itering/darwinia.js/node_modules/@polkadot/typegen/cjs/generate/lookup.js:210:187
    at Array.map (<anonymous>)
    at generateLookupTypes (/Users/lk/jsProject/itering/darwinia.js/node_modules/@polkadot/typegen/cjs/generate/lookup.js:207:26)
    at /Users/lk/jsProject/itering/darwinia.js/node_modules/@polkadot/typegen/cjs/generate/lookup.js:258:5
    at Array.reduce (<anonymous>)
    at generateLookup (/Users/lk/jsProject/itering/darwinia.js/node_modules/@polkadot/typegen/cjs/generate/lookup.js:250:11)
    at generateDefaultLookup (/Users/lk/jsProject/itering/darwinia.js/node_modules/@polkadot/typegen/cjs/generate/lookup.js:271:3)
    at main (/Users/lk/jsProject/itering/darwinia.js/packages/typegen/src/interfacesTs.ts:60:5)
    at Object.<anonymous> (/Users/lk/jsProject/itering/darwinia.js/packages/typegen/scripts/darwinia-types-internal-interfaces.cjs:34:1)
```

**Comment by jacogr** [comment]
There is no handling for Range (or RangeInclusive) types. Instead of doing it in the dark and hoping for the best, without testcases.

PRs very welcome, adjustments should go into https://github.com/polkadot-js/api/blob/master/packages/typegen/src/generate/tsDef.ts
