### ISSUE TITLE
Import the polkadot-api in React-Native, The error summary

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/api#481]
**polkadot Api version** : 
```
    "@polkadot/api": "^0.33.17",
    "@polkadot/rpc-provider": "^0.33.17"
```
**This React-Native project create way is** :
 `react-native init Project`
```
cd Project
react-native run-android
```

**packages**:
```
"dependencies": {
    "axios": "0.18.0",
    "ethers": "3.0.27",
    "identicon.js": "2.3.2",
    "mobx": "^4.3.1",
    "mobx-react": "5.2.5",
    "moment": "2.22.2",
    "react": "16.4.2",
    "react-native": "0.56.0",
    "react-native-camera": "1.2.0",
    "react-native-modal": "6.5.0",
    "react-native-permissions": "1.1.1",
    "react-native-qrcode-svg": "5.1.0",
    "react-native-sensitive-info": "5.2.4",
    "react-native-snackbar": "0.5.0",
    "react-native-svg": "6.5.2",
    "react-native-vector-icons": "5.0.0",
    "react-navigation": "2.12.1",
    "@polkadot/api": "^0.33.17",
    "@polkadot/rpc-provider": "^0.33.17"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "23.4.2",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-preset-react-native": "5.0.2",
    "enzyme": "3.5.0",
    "enzyme-adapter-react-16": "1.3.0",
    "eslint-config-rallycoding": "3.2.0",
    "jest": "23.5.0",
    "jsdom": "12.0.0",
    "react-native-mock-render": "0.1.1",
    "react-test-renderer": "16.4.2",
    "rimraf": "^2.6.2"
  },
```

**When I import the @polkadot/api to **React Native** project. get the error**:
```
error: bundling failed: Error: Unable to resolve module `core-js/modules/es6.regexp.to-string` from `/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/@polkadot/util/logger.js`: Module `core-js/modules/es6.regexp.to-string` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

```
![_ _20181217193346](https://user-images.githubusercontent.com/34789555/50085161-373fe500-0234-11e9-8c66-caabe7751988.png)

```
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/@polkadot/util/logger.js","targetModuleName":"core-js/modules/es6.regexp.to-string","message":"Unable to resolve module `core-js/modules/es6.regexp.to-string` from `/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/@polkadot/util/logger.js`: Module `core-js/modules/es6.regexp.to-string` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `core-js/modules/es6.regexp.to-string` from `/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/@polkadot/util/logger.js`: Module `core-js/modules/es6.regexp.to-string` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `core-js/modules/es6.regexp.to-string` from `/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/@polkadot/util/logger.js`: Module `core-js/modules/es6.regexp.to-string` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:1306)\n    at ResolutionRequest.resolveDependency (/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)\n    at DependencyGraph.resolveDependency (/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)\n    at Object.resolve (/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/lib/transformHelpers.js:116:25)\n    at dependencies.map.result (/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)\n    at Array.map (<anonymous>)\n    at resolveDependencies (/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)\n    at /media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33\n    at Generator.next (<anonymous>)\n    at step (/media/threebody/DATA/Desktop/github/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)"}
processBundleResult
    BundleDownloader.java:285
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:163
execute
    RealCall.java:153
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764

```

**Comment by jacogr** [comment]
After initial chat, the dev-deps ends up being

```
"devDependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "23.4.2",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-preset-react-native": "5.0.2",
    "enzyme": "3.5.0",
    "enzyme-adapter-react-16": "1.3.0",
    "eslint-config-rallycoding": "3.2.0",
    "jest": "23.5.0",
    "jsdom": "12.0.0",
    "react-native-mock-render": "0.1.1",
    "react-test-renderer": "16.4.2",
    "rimraf": "^2.6.2"
  },
```

So this seems to be a 7.2 vs 7-beta issue. We really want these to just work without tweaking, so need to investigate.

**Comment by jacogr** [comment]
Ok, with the above 2 PRs, the initial issues are resolved as of ^0.33.34 onwards. 

This includes the original core-js issue, the TextEncoder/Decoder issue and the additional safe-buffer requiring buffer issue. However, it is still not operational on RN as of yet, the environment has some peculiarities. Currently looking into the stream/streamCtor issue, so not out of the woods.

**Comment by jiangfuyao** [comment]
**Now, this is error is resolved**,  
I add    "[node-libs-react-native](https://www.npmjs.com/package/node-libs-react-native)": "^1.0.3" , and the  ` "@babel/xxxxxxx": "7.0.0-beta.47" ` **without** `^`,
**now my packages** :
```
"dependencies": {
    "@polkadot/api": "^0.33.25",
    "@polkadot/rpc-provider": "^0.33.25",
    "@polkadot/rpc-core": "^0.33.25",
    "axios": "0.18.0",
    "core-js": "^2.6.0",
    "ethers": "3.0.27",
    "identicon.js": "2.3.2",
    "mobx": "^4.3.1",
    "mobx-react": "5.2.5",
    "moment": "2.22.2",
    "node-libs-react-native": "^1.0.3",
    "react": "16.6.3",
    "react-native": "0.56.0",
    "react-native-camera": "1.2.0",
    "react-native-modal": "6.5.0",
    "react-native-permissions": "1.1.1",
    "react-native-qrcode-svg": "5.1.0",
    "react-native-sensitive-info": "5.2.4",
    "react-native-snackbar": "0.5.0",
    "react-native-svg": "6.5.2",
    "react-native-vector-icons": "5.0.0",
    "react-navigation": "2.12.1"
  },
  "devDependencies": {
    "@babel/core": "^7.2.0",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "23.4.2",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-preset-react-native": "5.0.2",
    "enzyme": "3.5.0",
    "enzyme-adapter-react-16": "1.3.0",
    "eslint-config-rallycoding": "3.2.0",
    "jest": "23.5.0",
    "jsdom": "12.0.0",
    "react-native-mock-render": "0.1.1",
    "react-test-renderer": "16.4.2",
    "rimraf": "^2.6.2",
    "@polkadot/dev": "^0.22.12",
    "@polkadot/ts": "^0.1.43"
  },
```
**But, got another error** :

![_ _20181218110225](https://user-images.githubusercontent.com/34789555/50134074-5fc5ee80-02c9-11e9-817f-40972e2df631.png)
![_ _20181218110232](https://user-images.githubusercontent.com/34789555/50134078-648aa280-02c9-11e9-8561-5c574084a0e8.png)
```
undefined is not a function (evaluating 'Object.setPrototypeOf(chalk, Chalk.prototype)')
Chalk
    index.js:39:24
<unknown>
    index.js:226:17
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:168:36
metroRequire
    require.js:152:20
<unknown>
    logger.js:17:36
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:168:36
metroRequire
    require.js:152:20
<unknown>
    index.js:36:37
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:168:36
metroRequire
    require.js:152:20
<unknown>
    index.js:12:12
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:168:36
metroRequire
    require.js:152:20
<unknown>
    index.js:21:38
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:168:36
metroRequire
    require.js:152:20
<unknown>
    index.js:8:23
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:168:36
metroRequire
    require.js:152:20
<unknown>
    index.js:4
loadModuleImplementation
    require.js:237:12
guardedLoadModule
    require.js:161:45
metroRequire
    require.js:152:20
global code
    
```

**Comment by jiangfuyao** [comment]
API feedback color is not needed for the time being, so it is removed "chalk" temporarily. Record, solve in the future.

Then got an new error:
![_ _20181218144355](https://user-images.githubusercontent.com/34789555/50136801-e4b60580-02d3-11e9-90bf-73b4feed780d.png)
I am fixing it.....

**Comment by jacogr** [comment]
The color/chalk we can remove, it only gets used in the client repo really.

**Comment by jiangfuyao** [comment]
>undefined is not a function (evaluating '()type.toUpperCase() + ":").padStart(16)')

Solution for now is:
Polkadot Api file change:
**/node_modules/@polkadot/util/logger.js**
```
import _ from "lodash"; 
const type = _.padStart(`${_type.toUpperCase()}:`,16); 
```

**/node_modules/@polkadot/dev/scripts/polkadot-dev-yarn-only.js **
```
import _ from "lodash";
const blank = _.padStart('',75);
```

**Reference**  : <https://github.com/facebook/react-native/issues/18375>

**Comment by jiangfuyao** [comment]
When to import the **@polkadot/keyring**  have the issue:**BASE_MAP.fill(255)**
![_ _20181218193908](https://user-images.githubusercontent.com/34789555/50152379-6b7fd800-02fe-11e9-963e-f4c12d20fe08.png)


change the code of: node_moduls/base-x.index.js:13
```
  // BASE_MAP.fill(255)
  for(let i=0; i < BASE_MAP.length;i++) {
    BASE_MAP[i] = 255
  }
```
There is only one temporary way.

**Comment by jiangfuyao** [comment]
## Now the @polkadot packages import to RN state:


- [ ] //const { ApiPromise } = require('@polkadot/api/promise'); //class extends issue
- [x]  const { testApi1 } = require('@polkadot/dev'); // import is ok
- [x]  const { testapi2 } = require('@polkadot/jsonrpc'); // import is ok
- [x]  const { testapi3 } = require('@polkadot/extrinsics'); //import is ok 
- [x]  const { testapi4 } = require('@polkadot/keyring'); // import is ok
- [x]  const { testapi6 } = require('@polkadot/rpc-provider'); //import is ok
- [x]  const { testapi11 } = require('@polkadot/util'); // import is ok
- [x]  const { WsProvider } = require('@polkadot/rpc-provider');  //import is ok
- [x]  const { testapi12 } = require('@polkadot/util-crypto'); //import is ok
- [ ] // const { testapi7 } = require('@polkadot/rpc-rx'); //class extends issue
- [ ] // const { testapi5 } = require('@polkadot/rpc-core'); //class extends issue
- [ ] // const { testapi8 } = require('@polkadot/storage'); //class extends issue
- [ ] //const { testapi9 } = require('@polkadot/ts'); // The development server returned response error code: 500 ()
- [ ] // const { testapi10 } = require('@polkadot/types'); //class extends issue

**Comment by 452MJ** [comment]
Unable to resolve module `util` from `node_modules/@polkadot/util/polyfill/textDecoder.js`: util could not be found within the project.

**Comment by 452MJ** [comment]
![Simulator Screen Shot - iPhone 11 - 2019-11-14 at 18 16 57](https://user-images.githubusercontent.com/13673008/68848411-401e8c80-070b-11ea-92ec-0179d5ebec3b.png)

**Comment by 452MJ** [comment]
I fix it follow the repo [https://github.com/jacogr/pjs-rn-rncli](https://github.com/jacogr/pjs-rn-rncli).
