### ISSUE TITLE
error raised if RPC response takes more than 60s

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/api#4811]
It seems like the default configs are such that an RPC request taking more than 60s causes this error: 

```
2022-05-09 17:47:32        RPC-CORE: getStorageSize(key: StorageKey, at?: BlockHash): u64:: No response received from RPC endpoint in 60s
2022-05-09 17:47:32        RPC-CORE: getStorageSize(key: StorageKey, at?: BlockHash): u64:: No response received from RPC endpoint in 60s
2022-05-09 17:47:32        RPC-CORE: getStorageSize(key: StorageKey, at?: BlockHash): u64:: No response received from RPC endpoint in 60s
Error: No response received from RPC endpoint in 60s
    at WsProvider.value (/Users/kianenigma/Desktop/Parity/polkadot-runtime-prom-exporter/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:394:32)
    at Timeout._onTimeout (/Users/kianenigma/Desktop/Parity/polkadot-runtime-prom-exporter/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:503:166)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-05-09 17:47:42        RPC-CORE: health(): Health:: No response received from RPC endpoint in 60s
```

I am not sure if this error is actually killing the request, or is it just a warning. Either way, it would be a good to have a way to configure this max timeout.

**Comment by jacogr** [comment]
It is configurable, see https://github.com/polkadot-js/api/pull/4758

**Comment by kianenigma** [comment]
Thanks!
