### ISSUE TITLE
Vec<Option<X>> type not supported in typegen as tx argument

### ISSUE THREAD

**Issue by RyuH1** [polkadot-js/api#4813]
I ran into the following issue when running typegen for the metadata from my runtime

```
$ ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --package automata-typings/interfaces --endpoint ./fst_2.json --output ./src/interfaces
Generating from metadata, 132,496 bytes
No custom definitions found.
/Users/ryuh1/automata/automata-typings/src/interfaces/augment-api-consts.ts
        Generating
        Writing

/Users/ryuh1/automata/automata-typings/src/interfaces/augment-api-errors.ts
        Generating
        Writing

/Users/ryuh1/automata/automata-typings/src/interfaces/augment-api-events.ts
        Generating
        Writing

/Users/ryuh1/automata/automata-typings/src/interfaces/augment-api-query.ts
        Generating
        Writing

/Users/ryuh1/automata/automata-typings/src/interfaces/augment-api-rpc.ts
        Generating
        Writing

/Users/ryuh1/automata/automata-typings/src/interfaces/augment-api-tx.ts
        Generating
/Users/ryuh1/automata/automata-typings/node_modules/@polkadot/typegen/cjs/util/derived.js:73
        throw new Error(`Unhandled subtype in Vec, ${(0, _util.stringify)(subDef)}`);
              ^
Error: Unhandled subtype in Vec, {"info":9,"type":"Option<U256>","sub":{"info":10,"type":"U256"}}
    at getSimilarTypes (/Users/ryuh1/automata/automata-typings/node_modules/@polkadot/typegen/cjs/util/derived.js:73:15)
    at /Users/ryuh1/automata/automata-typings/node_modules/@polkadot/typegen/cjs/generate/tx.js:94:59
    at Array.map (<anonymous>)
    at /Users/ryuh1/automata/automata-typings/node_modules/@polkadot/typegen/cjs/generate/tx.js:92:34
    at Array.map (<anonymous>)
    at Type.map (/Users/ryuh1/automata/automata-typings/node_modules/@polkadot/types-codec/cjs/abstract/AbstractArray.js:209:27)
    at /Users/ryuh1/automata/automata-typings/node_modules/@polkadot/typegen/cjs/generate/tx.js:77:82
    at Array.map (<anonymous>)
    at /Users/ryuh1/automata/automata-typings/node_modules/@polkadot/typegen/cjs/generate/tx.js:70:8
    at writeFile (/Users/ryuh1/automata/automata-typings/node_modules/@polkadot/typegen/cjs/util/file.js:23:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After checking the code in https://github.com/polkadot-js/api/blob/master/packages/typegen/src/util/derived.ts#L52L68
realized that such type seems not supported yet. Please correct me if I were wrong.

If that's the case. Is it possible to add support for such type in near future? I'll appreciate if action can be taken. However, if it's not feasible to do so, please also let me know so will modify the data definition used in my runtime accordingly.

**Comment by RyuH1** [comment]
FYI, Here is the definition of the tx in my runtime: https://github.com/automata-network/automata-common/blob/915dc610e9a6a8e6a15f5f58fcf64c80bd88a7fb/frame/daoportal/src/lib.rs#L403

**Comment by jacogr** [comment]
The issue with the "unsupported" paths is that they are not being tested. So here we are always explicit, rather failing right up-front instead of "doing the wrong thing".

Support should be simple, but it is the same thing - without actually testing it it would probably mean - try to support, get feedback on the next release it is missing something, rinse, repeat.

So for case that does not occur in the base Substrate or Polkadot code, tested PRs are always very welcome.

**Comment by jacogr** [comment]
Do you have a link to the metadata for the chain or just the chain itself? (As a testcase for this generation)
