### ISSUE TITLE
typegen: types generation from defs throws `TypeDefInfo.Enum: Not implemented

### ISSUE THREAD

**Issue by filo87** [polkadot-js/api#4837]
I am trying to generate custom types definitions in the following branch of our project:

https://github.com/embrio-tech/centrifuge-subql/tree/13-implement-custom-types-for-pools-chain-state-getters

After extending the `package.json` to include the ts-node calls for type generation and also updated `tsconfig.json` as following:

`package.json`
``` json
{
  "name": "@centrifuge/pools-subql",
  "version": "0.0.4",
  "description": "Subquery for the pools functionality",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc -b",
    "prepack": "rm -rf dist && npm build",
    "test": "jest",
    "codegen": "./node_modules/.bin/subql codegen",
    "generate:defs": "ts-node --skip-project node_modules/.bin/polkadot-types-from-defs --package centrifuge-subql/api-interfaces --endpoint ./src/api-interfaces/cfg.json --input ./src/api-interfaces",
    "generate:meta": "ts-node --skip-project node_modules/.bin/polkadot-types-from-chain --endpoint ./src/api-interfaces/cfg.json --output ./src/api-interfaces --strict",
    "interface-build": "yarn generate:defs && yarn generate:meta && yarn build"
  },
  "homepage": "https://github.com/centrifuge/pools-subql",
  "repository": "github:centrifuge/pools-subql",
  "files": [
    "dist",
    "schema.graphql",
    "project.yaml"
  ],
  "author": "Centrifuge",
  "license": "MIT",
  "dependencies": {
    "@polkadot/api": "^8"
  },
  "devDependencies": {
    "@polkadot/typegen": "^8",
    "@polkadot/types": "^8",
    "@subql/cli": "latest",
    "ts-node": "^8.6.2",
    "typescript": "^4.4.4"
  },
  "exports": {
    "chaintypes": "./src/chaintypes.ts"
  },
  "resolutions": {
    "ipfs-unixfs": "6.0.6"
  }
}
```

`tsconfig.json`
``` json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "declaration": true,
    "importHelpers": true,
    "resolveJsonModule": true,
    "module": "commonjs",
    "outDir": "dist",
    "rootDir": "src",
    "target": "es2017",
    "paths": {
      "centrifuge-subql/*": ["./src/*"],
      "@polkadot/api/augment": ["./src/api-interfaces/augment-api.ts"],
      "@polkadot/types/augment": ["./src/api-interfaces/augment-types.ts"]
    }
  },
  "include": ["./src/**/*", "./node_modules/@subql/types/dist/global.d.ts"],
  "exports": {
    "chaintypes": "./src/chaintypes.ts"
  }
}
```
Some files are created correctly:
- `types.ts`
- `augment-types.ts`
- `lookup.ts`

However when running the `yarn generate:defs` command I get the following error:

``` bash
yarn generate:defs                      
yarn run v1.22.18
$ ts-node --skip-project node_modules/.bin/polkadot-types-from-defs --package centrifuge-subql/api-interfaces --endpoint ./src/api-interfaces/cfg.json --input ./src/api-interfaces
/Users/Development/cfg-development/centrifuge-subql/src/api-interfaces/types.ts
        Generating
        Writing

/Users/Development/cfg-development/centrifuge-subql/src/api-interfaces/augment-types.ts
        Generating
        Writing

/Users/Development/cfg-development/centrifuge-subql/src/api-interfaces/lookup.ts
        Generating
        Writing


/Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/util/formatting.js:148
    throw new Error(`TypeDefInfo.Enum: Not implemented on ${(0, _util.stringify)(typeDef)}`);
          ^
Error: TypeDefInfo.Enum: Not implemented on {"info":4,"lookupIndex":336,"type":"{\"_enum\":{\"NoChange\":\"Null\",\"NewValue\":\"Vec<(PalletPoolsTrancheTrancheType,Option<u32>)>\"}}","docs":[],"namespace":"orml_traits::Change","sub":[{"info":8,"type":"Null","index":0,"name":"NoChange"},{"info":19,"lookupIndex":332,"type":"Vec<(PalletPoolsTrancheTrancheType,Option<u32>)>","docs":[],"namespace":"","sub":{"info":17,"lookupIndex":333,"type":"(PalletPoolsTrancheTrancheType,Option<u32>)","docs":[],"namespace":"","sub":[{"docs":[],"info":15,"lookupIndex":334,"lookupName":"PalletPoolsTrancheTrancheType","type":"Lookup334"},{"info":9,"lookupIndex":270,"type":"Option<u32>","docs":[],"namespace":"Option","sub":{"info":10,"lookupIndex":4,"type":"u32","docs":[],"namespace":""}}]},"typeName":"Value","index":1,"name":"NewValue"}],"name":"tranches","typeName":"Change"}
    at Object.4 (/Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/util/formatting.js:148:11)
    at formatType (/Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/util/formatting.js:281:34)
    at /Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:235:108
    at Array.map (<anonymous>)
    at Object.tsStruct (/Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:234:20)
    at /Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/generate/lookup.js:210:187
    at Array.map (<anonymous>)
    at generateLookupTypes (/Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/generate/lookup.js:207:26)
    at /Users/Development/cfg-development/centrifuge-subql/node_modules/@polkadot/typegen/cjs/generate/lookup.js:258:5
    at Array.reduce (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

All @polkadot/api package versions are "8.4.2"

Any idea how to fix this?

**Comment by jacogr** [comment]
Not all paths are implemented for typegen - since these paths do not appear in Substrate master, they are untested and unverified to ensure that they push out the correct outputs. Rather be explicit instead of doing the wrong things because it has not been checked.

So in cases like this,

- a tested PR is always appreciated (e.g. see a contributed examples [here](https://github.com/polkadot-js/api/pull/4743) and [here](https://github.com/polkadot-js/api/pull/4720) that extend the reach of the typegen)
- with a link to a running chain, can put this in the queue, i.e. can extract the metadata and run through typegen on those cases (same as the above, the work just falls into my queue by providing a testcase to check against for validity)
