### ISSUE TITLE
Broken kusama StakingLedger types 

### ISSUE THREAD

**Issue by ma-shulgin** [polkadot-js/api#4854]
Hello! I get an error when call Staking.Ledger storage function on some blocks with 1050 spec version. 
```
runProgram(async () => {
    let api = await kusama()
    let at = await api.at('0xb645c7be25ab36bb1e70ebb5541fc238367c206124427b9c6871b2581a5a0f2e')
    let ledger = await at.query.staking.ledger('F4qoxcCDNyYoMKiu4LNXkQQaJVnMDNhoABGtVVWwmsf4kdZ')
    console.log(ledger)
})
```

Error:
```
2022-05-11 15:09:46        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage staking.ledger:: createType(StakingLedger):: {"stash":"AccountId","total":"Compact<Balance>","active":"Compact<Balance>","unlocking":"Vec<UnlockChunk>","lastReward":"Option<EraIndex>"}:: Decoded input doesn't match input, received 0x6e394ffb3e188c892eb74296cd97eba661129b2d0d9d15a2da05f32f826fdd030b10b3fb87f8080b10b3fb87f80800 (47 bytes), created 0x6e394ffb3e188c892eb74296cd97eba661129b2d0d9d15a2da05f32f826fdd030b10b3fb87f8080b10b3fb87f8080000 (48 bytes)
Error: Unable to decode storage staking.ledger:: createType(StakingLedger):: {"stash":"AccountId","total":"Compact<Balance>","active":"Compact<Balance>","unlocking":"Vec<UnlockChunk>","lastReward":"Option<EraIndex>"}:: Decoded input doesn't match input, received 0x6e394ffb3e188c892eb74296cd97eba661129b2d0d9d15a2da05f32f826fdd030b10b3fb87f8080b10b3fb87f80800 (47 bytes), created 0x6e394ffb3e188c892eb74296cd97eba661129b2d0d9d15a2da05f32f826fdd030b10b3fb87f8080b10b3fb87f8080000 (48 bytes)
    at RpcCore._newType (/Users/eldar/dev/polka-test/node_modules/@polkadot/rpc-core/cjs/bundle.js:477:13)
    at RpcCore._formatStorageData (/Users/eldar/dev/polka-test/node_modules/@polkadot/rpc-core/cjs/bundle.js:423:17)
    at RpcCore._formatOutput (/Users/eldar/dev/polka-test/node_modules/@polkadot/rpc-core/cjs/bundle.js:397:19)
    at RpcCore._formatResult (/Users/eldar/dev/polka-test/node_modules/@polkadot/rpc-core/cjs/bundle.js:222:27)
    at callWithRegistry (/Users/eldar/dev/polka-test/node_modules/@polkadot/rpc-core/cjs/bundle.js:250:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

So it tries to decode with [this](https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L108) type. But if use [first](https://github.com/polkadot-js/api/blob/master/packages/types/src/interfaces/staking/types.ts#L333) `StakingLedger`  interface instead of it, It will work (but other blocks of 1050 version will fail). 

Is it possible to make all v1050 blocks decodable?

**Comment by jacogr** [comment]
These seems to be something missing in the full type definitions for Kusama, would need investigation, something is amis here - https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L98-L111
