### ISSUE TITLE
Generate typescript defs error on `Range`

### ISSUE THREAD

**Issue by saboonikhil** [polkadot-js/api#4884]
Using **polkadot/typegen v8.6.2** post fix by #4802

```
$ ts-node -r tsconfig-paths/register packages/types/scripts/generate.ts
packages/types/src/interfaces/types.ts
        Generating
        Extracting interfaces for index
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'BlockNumber' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'Index' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'Moment' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
        Extracting interfaces for orderbook
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'BlockNumber' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'Index' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'Moment' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
        Extracting interfaces for predictionMarkets
                WARN: Overwriting duplicated type 'Address' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'BlockNumber' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'Index' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index
                WARN: Overwriting duplicated type 'Moment' @polkadot/types/interfaces/runtime -> @zeitgeistpm/types/interfaces/index

/Users/nikhilsaboo/Projects/tools/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:79
  const keys = named.map(def => {
                     ^
Error: Enum: MarketPeriod: Unhandled type Range, {"info":11,"name":"Block","type":"Range<BlockNumber>","sub":{"info":10,"type":"BlockNumber"},"index":0}
    at /Users/nikhilsaboo/Projects/tools/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:112:15
    at Array.map (<anonymous>)
    at Object.tsEnum (/Users/nikhilsaboo/Projects/tools/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:79:22)
    at /Users/nikhilsaboo/Projects/tools/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:297:41
    at Array.map (<anonymous>)
    at generateInterfaces (/Users/nikhilsaboo/Projects/tools/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:292:32)
    at generateTsDefFor (/Users/nikhilsaboo/Projects/tools/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:313:22)
    at /Users/nikhilsaboo/Projects/tools/node_modules/@polkadot/typegen/cjs/generate/tsDef.js:344:7
    at Array.forEach (<anonymous>)
```

**Comment by saboonikhil** [comment]
You should find the static metadata [here](https://github.com/zeitgeistpm/tools/blob/main/packages/types/src/metadata/static-latest.ts).

Cheers to your good work!
