### ISSUE TITLE
Error: findMetaCall: Unable to find Call with index [0, 0]/[0,0]

### ISSUE THREAD

**Issue by CertainLach** [polkadot-js/api#4899]
Running

polkadot-types-from-chain --endpoint metadata.json --output src/ --package .

Using polkadot.js v8.6.2 (fails with same error on newer versions)

With this metadata:
https://gist.githubusercontent.com/CertainLach/ff33bd12309639b457a85904c951e381/raw/73a7e2653fc7bb8cd68422763a052e5dd5d9e2e3/metadata.json

Fails with this error:
```
Error: findMetaCall: Unable to find Call with index [0, 0]/[0,0]
    at assert (node_modules/@polkadot/util/cjs/assert.js:37:11)
    at assertReturn (node_modules/@polkadot/util/cjs/assert.js:47:3)
    at TypeRegistry.findMetaCall (node_modules/@polkadot/types/cjs/create/registry.js:329:35)
    at decodeCallViaU8a (node_modules/@polkadot/types/cjs/generic/Call.js:62:34)
    at decodeCall (node_modules/@polkadot/types/cjs/generic/Call.js:90:12)
    at new GenericCall (node_modules/@polkadot/types/cjs/generic/Call.js:121:21)
    at new Type (node_modules/@polkadot/types/cjs/create/registry.js:368:16)
    at createFromValue (node_modules/@polkadot/types-codec/cjs/base/Enum.js:92:79)
    at decodeEnum (node_modules/@polkadot/types-codec/cjs/base/Enum.js:134:10)
    at new Enum (node_modules/@polkadot/types-codec/cjs/base/Enum.js:163:156)
```

This was previously fixed (#4793), but broken again with upgrade to polkadot-v0.9.22 branch of substrate

**Comment by jacogr** [comment]
There has been no "fix" for this - the API expects something to fall back to for a default (non-value call) and this is set at 0,0 which is generally occupied by the first call in the system pallet across all chains. In this case the indexes has been moved and there is no indexes at that location.

There is probably much more broken API-wise on this chain than just typegen, all `createType('Call')` calls will fail.
