### ISSUE TITLE
getBlock - Unable to catch some transactions

### ISSUE THREAD

**Issue by nomotobori1** [polkadot-js/api#5291]
Hello everyone, when I ran getBlock function as followed const Block = api.getBlock(blockHash), I got an unexpected error.
Please tell me politely why the error occurs, how to solve the problem.

  - BlockNumber:
`12533787`
`12564747`
`12586563`

  - BlockHash:
`0xc71a360ace01bbbd3c3053e836201a9280b2a768e906a16f552cc3a02fab3464`
`0x14d7eb3ff50b614b08ac41bb1f1247799bcdb28f621c2aca4866a64b1827a77e`
`0x111b0d96cd6f5c31b7f9efe6d477d3dfbc80fa9966d9f99384a223a1eb72c046`

  - Error msg:
```
[2022-10-20T15:49:20.415] [ERROR] default - TypeError: (0 , _classPrivateFieldLooseBase2.default)(...)[_raw].toBn is not a function
at Type.toU8a (/var/task/node_modules/@polkadot/types/codec/Compact.cjs:188:96)
at Map.toU8a (/var/task/node_modules/@polkadot/types/codec/Struct.cjs:280:24)
at Map.toU8a (/var/task/node_modules/@polkadot/types/codec/Struct.cjs:280:24)
at Map.toU8a (/var/task/node_modules/@polkadot/types/codec/Struct.cjs:280:24)
at Type.toU8a (/var/task/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:353:84)
at Type.get hash (/var/task/node_modules/@polkadot/types/codec/Base.cjs:39:36)
at Type.get hash [as hash] (/var/task/node_modules/@polkadot/types/extrinsic/Extrinsic.cjs:265:87)
at /var/task/BlockHandler/index.js:175:84
at Array.map (<anonymous>)
at Type.map (/var/task/node_modules/@polkadot/types/codec/AbstractArray.cjs:187:27)
```

  - Source code:
```
const { ApiPromise, WsProvider } = require('@polkadot/api');
async () => {
  const provider = new WsProvider('wss://rpc.polkadot.io/');
  const api = await ApiPromise.create({ provider });
  const Block = api.getBlock(blockHash);
```

  - Version:
`Polkadot v0.9.28`

  - Environment:
```
"@polkadot/api": {
      "version": "6.12.1",
      "resolved": "https://registry.npmjs.org/@polkadot/api/-/api-6.12.1.tgz",
      "integrity": "sha512-RVdTiA2WaEvproM3i6E9TKS1bfXpPd9Ly9lUG/kVLaspjKoIot9DJUDTl97TJ+7xr8LXGbXqm448Ud0hsEBV8Q==",
      "requires": {
        "@babel/runtime": "^7.16.3",
        "@polkadot/api-derive": "6.12.1",
        "@polkadot/keyring": "^8.1.2",
        "@polkadot/rpc-core": "6.12.1",
        "@polkadot/rpc-provider": "6.12.1",
        "@polkadot/types": "6.12.1",
        "@polkadot/types-known": "6.12.1",
        "@polkadot/util": "^8.1.2",
        "@polkadot/util-crypto": "^8.1.2",
        "eventemitter3": "^4.0.7",
        "rxjs": "^7.4.0"
      }
}
```

  - Language:
    - [x] JavaScript

  - Explore:
https://polkadot.subscan.io/

**Comment by jacogr** [comment]
Please ensure you are on a current version of the API, this is very outdated -

```
"@polkadot/api": {
      "version": "6.12.1",
      "resolved": "https://registry.npmjs.org/@polkadot/api/-/api-6.12.1.tgz",
```
