### ISSUE TITLE
[BUG] Deno cannot compile since polkadot@0.2.12

### ISSUE THREAD

**Issue by Revolution1** [polkadot-js/api#5350]
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Here is a simple script to test this issue from version 0.2.11 to 0.2.17

```bash
for v in {11..17}; do
    file="polkadot.0.2.$v.ts"
    cat <<EOF >$file
import { WsProvider } from "https://deno.land/x/polkadot@0.2.$v/api/mod.ts";
await (new WsProvider("wss://rpc.polkadot.io")).disconnect();
console.log("OK");
EOF
    echo "try running 'deno run -A $file'"
    deno run -A $file

    echo "try compile and run with 'deno compile -A -o test.0.2.$v $file && ./test.0.2.$v'"
    deno compile -A -o "test.0.2.$v" $file && ./"test.0.2.$v"
    echo
done
```

Here is the output in my machine

```bash
try running 'deno run -A polkadot.0.2.11.ts'
OK
try compile and run with 'deno compile -A -o test.0.2.11 polkadot.0.2.11.ts && ./test.0.2.11'
Compile file:///tmp/test/polkadot.0.2.11.ts
Emit test.0.2.11
OK

try running 'deno run -A polkadot.0.2.12.ts'
error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.153.0/node/process.ts' does not provide an export named 'hrtime'
    at <anonymous> (https://esm.sh/v96/@substrate/smoldot-light@0.7.2/deno/smoldot-light.js:4:5277)
try compile and run with 'deno compile -A -o test.0.2.12 polkadot.0.2.12.ts && ./test.0.2.12'
Check file:///tmp/test/polkadot.0.2.12.ts
Compile file:///tmp/test/polkadot.0.2.12.ts
Emit test.0.2.12
error: Module not found

try running 'deno run -A polkadot.0.2.13.ts'
error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.153.0/node/process.ts' does not provide an export named 'hrtime'
    at <anonymous> (https://esm.sh/v96/@substrate/smoldot-light@0.7.2/deno/smoldot-light.js:4:5277)
try compile and run with 'deno compile -A -o test.0.2.13 polkadot.0.2.13.ts && ./test.0.2.13'
Check file:///tmp/test/polkadot.0.2.13.ts
Compile file:///tmp/test/polkadot.0.2.13.ts
Emit test.0.2.13
error: Module not found

try running 'deno run -A polkadot.0.2.14.ts'
OK
try compile and run with 'deno compile -A -o test.0.2.14 polkadot.0.2.14.ts && ./test.0.2.14'
Check file:///tmp/test/polkadot.0.2.14.ts
Compile file:///tmp/test/polkadot.0.2.14.ts
Emit test.0.2.14
error: Module not found

try running 'deno run -A polkadot.0.2.15.ts'
OK
try compile and run with 'deno compile -A -o test.0.2.15 polkadot.0.2.15.ts && ./test.0.2.15'
Check file:///tmp/test/polkadot.0.2.15.ts
Compile file:///tmp/test/polkadot.0.2.15.ts
Emit test.0.2.15
error: Module not found

try running 'deno run -A polkadot.0.2.16.ts'
OK
try compile and run with 'deno compile -A -o test.0.2.16 polkadot.0.2.16.ts && ./test.0.2.16'
Check file:///tmp/test/polkadot.0.2.16.ts
Compile file:///tmp/test/polkadot.0.2.16.ts
Emit test.0.2.16
error: Module not found

try running 'deno run -A polkadot.0.2.17.ts'
OK
try compile and run with 'deno compile -A -o test.0.2.17 polkadot.0.2.17.ts && ./test.0.2.17'
Check file:///tmp/test/polkadot.0.2.17.ts
Compile file:///tmp/test/polkadot.0.2.17.ts
Emit test.0.2.17
error: Module not found
```

* **My ENvironment**

```bash
(
    echo environment:
    set -x
    uname -a
    cat /etc/lsb-release
    deno --version
)
environment:
+/usr/bin/zsh:67> uname -a
Linux Me 5.15.74.2-microsoft-standard-WSL2 #1 SMP Wed Nov 2 19:50:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
+/usr/bin/zsh:68> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
+/usr/bin/zsh:69> deno --version
deno 1.28.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.1
typescript 4.8.3
```

**Comment by jacogr** [comment]
This is known -

`error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.153.0/node/process.ts' does not provide an export named 'hrtime'
    at <anonymous> (https://esm.sh/v96/@substrate/smoldot-light@0.7.2/deno/smoldot-light.js:4:5277)`
    
 It was an issue in smolldot which has been addressed.
 
On the second - have never seen this, so not sure what `error: Module not found` refers to.

**Comment by Revolution1** [comment]
To make sure it's not my laptop's problem, I ran this script in a fresh new virtualmachine in AWS, also got the same result.

Might be this kind of issue, I'm not sure
https://github.com/denoland/deno/issues/16427

**Comment by jacogr** [comment]
The linked issue is interesting, but not quite applicable as far as I can tell - in the build scripts we don't (yet) use `npm:...` specifiers, rather all imports are done via `esm.sh/...`. (At some point in the future will certainly swap, but as of now only the latest Deno stable release has full support, so not venturing there as of yet)

**Comment by Revolution1** [comment]
I've used many libs in my project, only polkadoljs has this problem, but anyway, I can still use 0.2.11.

Hope this issue can be resolved soon.

**Comment by jacogr** [comment]
Deno has a nice error message in master which will point to exactly which lib has an issue - at this point there is nowhere to even start looking (there really has been no build-time changes between 0.2.11 and current - the build environment has stayed the same since Deno was introduced). 

So really interested to see what it complains about, but my hands are tied atm due to lack of info to even start looking. I believe some library included along the way most probably does `npm:...`, which is currently non Deno compile supported. But that is a guess at best at this point.

**Comment by Revolution1** [comment]
Did a breif test using this script:
```bash
cat <<EOF >main.ts
import { WsProvider } from "https://deno.land/x/polkadot@0.2.17/api/mod.ts";
await (new WsProvider("wss://rpc.polkadot.io")).disconnect();
console.log("OK");
EOF

deno cache --lock-write --lock=deno.lock main.ts

function run_tests() {
    OUTPUT=output
    rm -f $OUTPUT/*
    mkdir -p $OUTPUT
    echo > result.txt

    for v in $(jq -r '.remote | keys[]' deno.lock | grep -v ".d.ts"); do
        file="$(echo $v | tr '/:' '-')"
        cat <<EOF >$OUTPUT/$file.ts
import * as mod from "$v";
export const x = mod;
console.log("OK");
EOF
        echo "try running 'deno run -A $OUTPUT/$file.ts'"
        deno run -A $OUTPUT/$file.ts

        echo "try compile and run with 'deno compile -A -o $OUTPUT/test.$file $OUTPUT/$file.ts && $OUTPUT/test.$file'"
        deno compile -A -o "$OUTPUT/test.$file" $OUTPUT/$file.ts && "$OUTPUT/test.$file"
        if [[ "$?" == 0 ]]; then
            echo "PASS: $v" >> result.txt
        else
            echo "FAIL: $v" >> result.txt
        fi
        echo
    done
}

echo > log.txt
run_tests | tee log.txt

echo "Failed libraries:"
grep FAIL result.txt
```

Results:
```
Failed libraries:
FAIL: https://deno.land/x/polkadot@0.2.17/api/base/Decorate.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/base/Getters.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/base/Init.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/base/index.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/bundle.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/index.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/promise/Api.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/promise/index.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/rx/Api.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/rx/index.ts
FAIL: https://deno.land/x/polkadot@0.2.17/api/types/index.ts
FAIL: https://deno.land/x/polkadot@0.2.17/rpc-provider/bundle.ts
FAIL: https://deno.land/x/polkadot@0.2.17/rpc-provider/index.ts
FAIL: https://deno.land/x/polkadot@0.2.17/rpc-provider/substrate-connect/index.ts
FAIL: https://esm.sh/@substrate/connect@0.7.17
FAIL: https://esm.sh/v99/@substrate/connect@0.7.17/deno/connect.js
```

this might help narrow down the cause

**Comment by Revolution1** [comment]
After some filtering of the result above, I'm pretty sure the root cause comes from this package!
`https://esm.sh/v99/@substrate/connect@0.7.17/deno/connect.js`

**Comment by jacogr** [comment]
I dug through https://esm.sh/v99/@substrate/connect@0.7.17/deno/connect.js and it certainly is not (as I speculated above), anything to do with `npm:...` prefixes. Worse, I cannot see anything really weird there either. 

I pasted the code from that file and re-formatted it, the imports seem all ok from there. Also no Node-specific stuff that could be weird. Seems like straight JS. (The dynamic imports _could_ be the cause here, i.e. it is always only known at runtime. But in this case that dynamic nature makes sense since the light specs are absolutely huge)

cc @wirednkod Nikos do you have any potential ideas on what _may_ go wrong here? (These are horrible since esm.sh does provide a level of indirection)

**Comment by jacogr** [comment]
Ok, so looking at all of this - this is a [known limitation of deno compile](https://deno.land/manual@v1.28.1/tools/compiler) aka explicitly listed under [unavailable in executables](https://deno.land/manual@v1.28.1/tools/compiler#unavailable-in-executables). 

While I do have a PR open that will work around this (for now) it will only work in the case where non-light is used and then at the cost of impacting basically users that do use light (in non-compile mode via running). So it is not something that really sits well with me at this point and is at best a hack to work around things in some short-term cases, kicking the can down the road. (Since light is the most important provider work that is ongoing)

I guess the "official response" at this exact moment is that deno compile is not supported when using this lib since we use dynamic imports along the way. (The above is not the only place, there are other places but those paths are not used in Deno, so by luck it doesn't have an issue with the same dynamic import in multiple locations) 

This response is not great, would certainly like everything to "just work", so I'll still look if there are options and I know @wirednkod is looking as well. However as of right now there is no real work-around.

**Comment by Revolution1** [comment]
Great work!

I'm a Devops developer, not very experienced in Javascript.
I have to deal with a lot of configurations (package.json, tsconfig, webpack config, etc..) and the fragile node_modules often breaks.
Deno really helps me a lot.
But since I'm adding more and more libs to the project, Deno became more problematic too 😭 .
I'm considering moving back to nodejs now.

But anyway, thank for the quick response!

**Comment by jacogr** [comment]
I think there is something that can be done, is-is. Try this approach if using deno w/ compilation, it _may_ do the trick.

```js
import { ApiPromise } from "https://deno.land/x/polkadot@0.2.17/api/promise/index.ts";
import { WsProvider } from "https://deno.land/x/polkadot@0.2.17/rpc-provider/ws/index.ts";

await Api.create({ provider: new WsProvider("wss://rpc.polkadot.io") });

console.log("OK");
```

It is pointing directly to the classes that you need. That _may_ just do it.
