### ISSUE TITLE
getStorage execution fails

### ISSUE THREAD

**Issue by forgetso** [polkadot-js/api#5387]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

This happens both on the command line and in polkadot apps. Overall method is [here](https://github.com/prosopo/contract/blob/f39c5c9911c291e2cdbea312639fb27b8bca9b30/src/contract/interface.ts#L182-L208).
```
            const promiseResult = await this.api.rx.call.contractsApi.getStorage(
                this.contract.address,
                storageEntry.layout.cell.key
            )
```

```
Calling contract getStorage
Contract address 5GM1AarMqZQYAnRJFHsk5Dd4XpC9RP5sCaUjsn8GDsL8KXNV
Storage key 0x0700000000000000000000000000000000000000000000000000000000000000
2022-12-22 15:35:48        RPC-CORE: call(method: Text, data: Bytes, at?: BlockHash): Bytes:: -32000: Client error: Execution failed: Runtime panicked: Bad input data provided to get_storage: Input buffer has still data left after decoding!
```

This was tested on substrate-contracts-node v0.14 and v0.23. In v0.14, the following output was present:

```
Version: 0.14.0-3943936

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   6: contracts_node_runtime::api::dispatch
   7: std::thread::local::LocalKey<T>::with
   8: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
   9: sc_executor::wasm_runtime::RuntimeCache::with_instance
  10: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  11: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  12: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  13: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: jsonrpsee_ws_server::server::background_task::{{closure}}
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: tokio::runtime::task::harness::poll_future
  21: tokio::runtime::task::harness::Harness<T,S>::poll
  22: std::thread::local::LocalKey<T>::with
  23: tokio::runtime::thread_pool::worker::Context::run_task
  24: tokio::runtime::thread_pool::worker::Context::run
  25: tokio::macros::scoped_tls::ScopedKey<T>::set
  26: tokio::runtime::thread_pool::worker::run
  27: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  28: tokio::runtime::task::harness::Harness<T,S>::poll
  29: tokio::runtime::blocking::pool::Inner::run
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
  33: start_thread
  34: clone


Thread 'tokio-runtime-worker' panicked at 'Bad input data provided to get_storage: Input buffer has still data left after decoding!', runtime/src/lib.rs:384

```

* **Please tell us about your environment:**

  - Version:
`substrate-contracts-node 0.14.0-3943936`
`substrate-contracts-node 0.23.0-8e0e25e6f0f`

```
    "@polkadot/api": "9.10.2",
    "@polkadot/api-contract": "9.10.2",
    "@polkadot/keyring": "^10.2.1",
    "@polkadot/types": "9.10.2",
    "@polkadot/types-codec": "9.10.2",
    "@polkadot/types-create": "9.10.2",
    "@polkadot/util": "^10.2.1",
    "@polkadot/util-crypto": "^10.2.1",
```

  - Environment:

    - [x] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
The issue is actually in the passed encoding here - the runtime call expects a `Vec<u8>` to be passed through, but the `...cell.key` is a `[u8; 32]`.

You should be able to force the encoding by passing hex itself for the key value, 

```js
const promiseResult = await this.api.rx.call.contractsApi.getStorage(
                this.contract.address,
                storageEntry.layout.cell.key.toHex()
            )
```

**Comment by forgetso** [comment]
Thanks very much, Jaco.
