### ISSUE TITLE
Multilocation v2 missing from api?

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/api#5570]
* **I'm submitting a ...**

  - [x] Support request about xcm version 2 MultiLocation not appearing on the api

* **What is the current behavior and expected behavior?**

I'm using `paritytech/parachains-integration-tests` to try and test relay chain 9370 with cumulus 9400 runtimes, so relay knows xcm v0,1,2 and cumulus knows xcm v2 and v3. Is there any way we can force back in the xcm MultiLocation v2 to exist - I think it's missing because v2 was just an alias to v1 and v1 was removed.

```
     Error: createType(Call):: Call: failed decoding xcmPallet.send:: Struct: failed on args: {"dest":"{\"_enum\":{\"V0\":\"XcmV0MultiLocation\",\"V1\":\"XcmV1MultiLocation\"}}","message":"{\"_enum\":{\"V0\":\"XcmV0Xcm\",\"V1\":\"XcmV1Xcm\",\"V2\":\"XcmV2Xcm\"}}"}:: Struct: failed on dest: {"_enum":{"V0":"XcmV0MultiLocation","V1":"XcmV1MultiLocation"}}:: Cannot map Enum JSON, unable to find 'v2' in v0, v1
      at createTypeUnsafe (node_modules/@polkadot/types-create/cjs/create/type.js:54:22)
      at TypeRegistry.createTypeUnsafe (node_modules/@polkadot/types/cjs/create/registry.js:276:52)
      at extrinsicFn (node_modules/@polkadot/types/cjs/metadata/decorate/extrinsics/createUnchecked.js:16:25)
      at Object.decorated [as send] (node_modules/@polkadot/api/cjs/base/Decorate.js:466:50)
      at buildDispatchable (src/utils.ts:96:42)
      at buildEncodedCallHex (src/utils.ts:84:39)
      at /home/gilescope/git/parachains-integration-tests/src/extrinsics.ts:26:47
      at step (dist/extrinsics.js:33:23)
      at Object.next (dist/extrinsics.js:14:53)
      at fulfilled (dist/extrinsics.js:5:58)
```

Is this a workaround to get around this?

* **Please tell us about your environment:**

  - Version: @polkadot/types 10.2.1 (latest)
  - Environment:

    - [x] Node.js

  - Language:

    - [x] TypeScript (include tsc --version) 4.9.5

**Comment by jacogr** [comment]
You will need to provide the exact code used. (And a link to a running chain this is operating on would be great, to look at metadata.

From the above it would seem that the type uses (check dest), knows v0/v1 as per the definition supplied by the types and v2 (unknown) is passed in.

**Comment by gilescope** [comment]
rococo is updated to xcm v3, and rockmine is still xcm v2 so that's an example of two running systems. According to the polkadot ui V2 is in both of them. Knowing only v0/v1 seems to be the problem but presumably polkadot-js only gets its types from polkadot-api? @NachoPal any ideas what's going on here?

**Comment by gilescope** [comment]
This is that the multiloctaion of xcmv2 is v1. It's just confusing - there's no actual problem here.
