### ISSUE TITLE
Configuring WebSocket Frame size

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#5621]
When the substrate pool is big (or another element that requires a single query), it is not possible to query it:

```
2023-04-28 09:44:41          API-WS: disconnected from wss://moonbeam.kaki.dev: 1009:: Frame size of 33746670 bytes exceeds maximum accepted frame size
2023-04-28 09:44:41        RPC-CORE: getHeader(hash?: BlockHash): Header:: disconnected from wss://moonbeam.kaki.dev: 1009:: Frame size of 33746670 bytes exceeds maximum accepted frame size
2023-04-28 09:44:41        RPC-CORE: pendingExtrinsics(): Vec<Extrinsic>:: disconnected from wss://moonbeam.kaki.dev: 1009:: Frame size of 33746670 bytes exceeds maximum accepted frame size
/home/crystalin/projects/moonbeam-tools/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:180
        const error = new Error(`disconnected from ${(0, _classPrivateFieldLooseBase2.default)(this, _endpoints)[_endpoints][(0, _classPrivateFieldLooseBase2.default)(this, _endpointIndex)[_endpointIndex]]}: ${event.code}:: ${event.reason || (0, _errors.getWSErrorString)(event.code)}`);
                      ^
Error: disconnected from wss://moonbeam.kaki.dev: 1009:: Frame size of 33746670 bytes exceeds maximum accepted frame size
    at W3CWebSocket.value (/home/crystalin/projects/moonbeam-tools/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:180:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/crystalin/projects/moonbeam-tools/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/crystalin/projects/moonbeam-tools/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/crystalin/projects/moonbeam-tools/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:513:28)
    at WebSocketConnection.emit (node:domain:489:12)
    at WebSocketConnection.drop (/home/crystalin/projects/moonbeam-tools/node_modules/websocket/lib/WebSocketConnection.js:475:14)
    at /home/crystalin/projects/moonbeam-tools/node_modules/websocket/lib/WebSocketConnection.js:303:18
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by jacogr** [comment]
Which version of the API? The `ws` module does not have that error message under Node.js. 

The previously used `websocket` module has - that has been dropped in [x-ws 11.0](https://github.com/polkadot-js/common/releases/tag/v11.0.1) as used in [api 10.0+](https://github.com/polkadot-js/api/releases/tag/v10.0.1)

**Comment by crystalin** [comment]
I confirm it works with recent version, sorry for the bad report
