### ISSUE TITLE
Cannot read properties of undefined (reading 'toHuman')

### ISSUE THREAD

**Issue by ioannist** [polkadot-js/api#5875]
* **I'm submitting a bug**

  - [ x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

for events and extrinsics:
`GenericExtrinsic<AnyTuple>
EventRecord.event: Event
`
calling
`e.toJSON()`
works fine

calling
`e.toHuman()`

```
 error: Error: Error in processBlockRange pipe: Error: Error in fetchBlockData: TypeError: Cannot read properties of undefined (reading 'toHuman')
      at file:///root/stakexyz-worker/indexer-activities/src/indexer.ts:138:48
      at Observable.init [as _subscribe] (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/observable/throwError.js:8:64)
      at Observable._trySubscribe (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
      at /root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
      at Object.errorContext (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
      at Observable.subscribe (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
      at /root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:17:31
      at OperatorSubscriber._this._error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
      at Subscriber.error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
      at Subscriber.error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
      at Subscriber.error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
      at Subscriber.error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/root/stakexyz-worker/indexer-activities/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30),
  durationMs: 1673
}

```
This used to work in v10.11.2 and i think it broke in 10.13.1

  - Version:
  - Environment:

    - [x ] Node.js
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ x] TypeScript (node18)
    - [ ] Other

**Comment by TarikGul** [comment]
Fix will be included in Mondays release
