### ISSUE TITLE
`TypeError: e.eq is not a function` while calling stakerRewardsMultiEras

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-js/api#5910]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
Here's the code: 
```ts
const stakerRewards = await api.derive.staking.stakerRewardsMultiEras(["1zugcag7cJVBtVRnFxv5Qftn7xKAnR6YJ9x4x3XLgGgmNnS"], [1477]);
console.log(stakerRewards);
```

While trying to execute it at `https://polkadot.js.org/apps/`, I get 
```
TypeError: e.eq is not a function
    at https://polkadot.js.org/apps/modu.feacb3d8bf903221.js:1:61475
    at Array.some (<anonymous>)
    at https://polkadot.js.org/apps/modu.feacb3d8bf903221.js:1:61456
    at Array.filter (<anonymous>)
    at xn (https://polkadot.js.org/apps/modu.feacb3d8bf903221.js:1:61442)
    at https://polkadot.js.org/apps/modu.feacb3d8bf903221.js:1:63668
    at e._subscribe (https://polkadot.js.org/apps/modu.e085438fec7e90eb.js:1:6819)
    at e._trySubscribe (https://polkadot.js.org/apps/modu.7c3b262d6289bfdf.js:2:30316)
    at https://polkadot.js.org/apps/modu.7c3b262d6289bfdf.js:2:30238
    at o (https://polkadot.js.org/apps/modu.7c3b262d6289bfdf.js:2:59112)
```

* **Please tell us about your environment:**
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-polkadot.luckyfriday.io#/js

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by mutantcornholio** [comment]
interesting, thanks!
