### ISSUE TITLE
Latest substrate, cannot decode event

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/api#782]
While sending, status from extrinsic submission -

<img width="495" alt="Polkadot:Substrate Portal 2019-03-16 17-48-45" src="https://user-images.githubusercontent.com/1424473/54478564-d9f80780-4813-11e9-99ca-7ffde3d32b86.png">

**Comment by jacogr** [comment]
Also appears using the e2e tests -

```
  console.log node_modules/@polkadot/util/logger.js:89
    2019-03-16 17:56:40          API-WS: handling: response = { jsonrpc: '2.0',
      result:
       '0x1800000000000000000100000001004a83f1c09be797bc3d9adce29818368b276a84e6b545ced492c25c948978d7f80e000000000100000002014a83f1c09be797bc3d9adce29818368b276a84e6b545ced492c25c948978d7f83930000000000000000000000000000000010000000203306721211d5404bd9da88e0204360a1a9ab8b87c66c1bc2fcdd37f3c2222cc204a83f1c09be797bc3d9adce29818368b276a84e6b545ced492c25c948978d7f8393000000000000000000000000000000000000000000000000000000000000000010000000000010d000100000001000000000000000000000000000000',
      id: 8 } id = 8

  console.error node_modules/@polkadot/util/logger.js:89
    2019-03-16 17:56:40        RPC-CORE: getStorage (key: StorageKey, block: Hash): StorageData:: Object.values(...)[index] is not a constructor

  console.error packages/rpc-rx/src/index.ts:114
    ExtError: getStorage (key: StorageKey, block: Hash): StorageData:: Object.values(...)[index] is not a constructor
        at call (/Users/jacogreeff/Projects/polkadot/api/packages/rpc-core/src/index.ts:124:15)
        at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by jacogr** [comment]
Would make sense, there is no 02.03 - 02 i3 balances, which has 3 events (0, 1, & 2).

**Comment by jacogr** [comment]
Logged on substrate repo https://github.com/paritytech/substrate/issues/2021

**Comment by jacogr** [comment]
Closed above, verified working.
