### ISSUE TITLE
Occur an error with Metadata new

### ISSUE THREAD

**Issue by freehere107** [polkadot-js/api#990]
```
const fromMetadata = require('@polkadot/storage/fromMetadata');
const rpcDataV3 = require('@polkadot/types/Metadata/v3/static');
const rpcDataV4 = require('@polkadot/types/Metadata/v4/static');
const Metadata = require('@polkadot/types/Metadata').default;
const StorageKey = require('@polkadot/types/primitive/StorageKey');

const metadata = new Metadata(rpcDataV3);
```
Get ERR
```
Unable to decode Struct on key 'magicNumber': MagicNumber: expected 0x6174656d, found 0x00000000
node_modules/@polkadot/util/u8a/concat.js:44
result.set(item, offset);
^

RangeError: Source is too large
at Uint8Array.set (<anonymous>)
at list.reduce (node_modules/@polkadot/util/u8a/concat.js:44:12)
at Array.reduce (<anonymous>)
at u8aConcat (node_modules/@polkadot/util/u8a/concat.js:43:15)
at Function.decodeMetadata (node_modules/@polkadot/types/Metadata/Metadata.js:46:63)
at new Metadata (node_modules/@polkadot/types/Metadata/Metadata.js:27:20)
at Object.<anonymous> (index.js:7:18)
at Module._compile (internal/modules/cjs/loader.js:805:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
at Module.load (internal/modules/cjs/loader.js:672:32)
```
with api
```
{
  "dependencies": {
    "@polkadot/api": "^0.80.1"
  }
}
```

**Comment by jacogr** [comment]
All the versioned tests actually does exactly this - added a sample (more readable, bypassing the utils), and it works as expected - https://github.com/polkadot-js/api/commit/3c4a57ba395f06bd515506eb39f14b15f37e0b87#diff-b949429ef76195ccfcac3964093e3913R11

**Comment by jacogr** [comment]
So looking through, the static is also a default export, so this should fix it - `const rpcDataV3 = require('@polkadot/types/Metadata/v3/static').default`;

**Comment by freehere107** [comment]
ok, fix ,thank you
